#   Copyright 2025 Neaera Consulting LLC
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Dockerfile to run the API
#

#########################################################################################
#
# Build container for Java app
#
FROM gradle:8.10-jdk22 AS builder
USER root
WORKDIR /home/app

# api
COPY ./j2735-2024-api/src               /home/app/j2735-2024-api/src
COPY ./j2735-2024-api/build.gradle      /home/app/j2735-2024-api
COPY ./j2735-2024-api/settings.gradle   /home/app/j2735-2024-api
COPY ./j2735-2024-api/gradle            /home/app/j2735-2024-api/gradle

# lib
COPY ./j2735-2024-ffm-lib/src/main/java     /home/app/j2735-2024-ffm-lib/src/main/java
COPY ./j2735-2024-ffm-lib/build.gradle      /home/app/j2735-2024-ffm-lib
COPY ./j2735-2024-ffm-lib/settings.gradle   /home/app/j2735-2024-ffm-lib

RUN cd j2735-2024-api && gradle clean build -xtest

## Entrypoint for debugging
#ENTRYPOINT ["tail", "-f", "/dev/null"]

########################################################################################
#
# Run container
#
FROM eclipse-temurin:22-jre-noble
WORKDIR /home
USER root

## Copy native library
COPY ./j2735-2024-ffm-lib/src/test/resources/j2735ffm/libasnapplication.so          /home

# Copy java app
COPY --from=builder /home/app/j2735-2024-api/build/libs/j2735-2024-api.jar          /home

#ENTRYPOINT ["tail", "-f", "/dev/null"]
ENTRYPOINT ["java", "--enable-native-access=ALL-UNNAMED", "-jar", "/home/j2735-2024-api.jar"]
