name: build
services:
  j2735-2024-api:
    build:
      context: .
      dockerfile: Dockerfile-build
    image: j2735-2024-api:latest
    restart: no
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./lib
        target: /lib/
      - type: bind
        source: ./generated-jextract
        target: /generated-jextract/
      - type: bind
        source: ./generated-files
        target: /generated-files/
