name: build-container-arm64
services:
  build-container-arm64:
    build:
      context: .
      dockerfile: Dockerfile-build
      args:
        TARGETARCH: arm64
        JEXTRACT_ARCH: aarch64
        LIBRARY_SUFFIX: -arm64
    image: build-container-arm64:latest
    restart: no
    volumes:
      - type: bind
        source: ./lib
        target: /build-lib/
      - type: bind
        source: ./generated-jextract
        target: /generated-jextract/
      - type: bind
        source: ./generated-files
        target: /generated-files/
