name: build-container-windows
services:
  build-container-windows:
    build:
      context: .
      dockerfile: Dockerfile-build-windows
      args:
        # Set BUILD_TYPE=Debug (e.g. '$env:BUILD_TYPE="Debug"' before 'docker compose build')
        # for an unoptimized build of the native exe suitable for friendly interactive debugging.
        BUILD_TYPE: ${BUILD_TYPE:-Release}
    image: build-container-windows:latest
    restart: no
    volumes:
      - type: bind
        source: ./lib
        target: C:\build-lib\
      - type: bind
        source: ./generated-jextract-windows
        target: C:\generated-jextract-windows\
      - type: bind
        source: ./generated-files
        target: C:\generated-files\
