POST http://localhost:4000/jer/uper/hex
Content-Type: application/json

{
  "messageId": 19,
  "value": {
    "SPAT": {
      "timeStamp": 400000,
      "name": "Example Name",
      "intersections": [
        {
          "id": {
            "region": 0,
            "id": 12111
          },
          "revision": 0,
          "status": "FFFF",
          "moy": 400000,
          "timeStamp": 35176,
          "enabledLanes": [
            1
          ],
          "states": [
            {
              "signalGroup": 2,
              "state-time-speed": [
                {
                  "eventState": "protected-Movement-Allowed",
                  "timing": {
                    "startTime": 22120,
                    "minEndTime": 22120,
                    "maxEndTime": 22121,
                    "likelyTime": 22120,
                    "confidence": 15,
                    "nextTime": 22220
                  },
                  "speeds": [
                    {
                      "type": "transit",
                      "speed": 250,
                      "confidence": "prec1ms",
                      "distance": 100,
                      "class": 1
                    },
                    {
                      "type": "greenwave",
                      "speed": 250,
                      "confidence": "prec100ms",
                      "distance": 50,
                      "class": 1
                    }
                  ]
                }
              ],
              "maneuverAssistList": [
                {
                  "connectionID": 1,
                  "queueLength": 0,
                  "availableStorageLength": 0,
                  "waitOnStop": true,
                  "pedBicycleDetect": true
                },
                {
                  "connectionID": 2,
                  "queueLength": 0,
                  "availableStorageLength": 0,
                  "waitOnStop": true,
                  "pedBicycleDetect": true
                }
              ]
            }
          ],
          "maneuverAssistList": [
            {
              "connectionID": 1,
              "queueLength": 0,
              "availableStorageLength": 0,
              "waitOnStop": true,
              "pedBicycleDetect": true
            },
            {
              "connectionID": 2,
              "queueLength": 0,
              "availableStorageLength": 0,
              "waitOnStop": true,
              "pedBicycleDetect": true
            }
          ]
        }
      ]
    }
  }
}