// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct AddGrpC_Altitude {
 *     AltitudeValue_t value;
 *     AltitudeConfidence_t confidence;
 *     asn_struct_ctx_t _asn_ctx;
 * } AddGrpC_Altitude_t
 * }
 */
public class AddGrpC_Altitude_t extends AddGrpC_Altitude {

    AddGrpC_Altitude_t() {
        // Should not be called directly
    }
}

