// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct AdvisorySpeed {
 *     AdvisorySpeedType_t type;
 *     SpeedAdvice_t *speed;
 *     SpeedConfidence_t *confidence;
 *     ZoneLength_t *distance;
 *     RestrictionClassID_t *Class;
 *     struct AdvisorySpeed__regional {
 *         struct {
 *             struct Reg_AdvisorySpeed **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_AdvisorySpeed *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } AdvisorySpeed_t
 * }
 */
public class AdvisorySpeed_t extends AdvisorySpeed {

    AdvisorySpeed_t() {
        // Should not be called directly
    }
}

