// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct ASN__PRIMITIVE_TYPE_s {
 *     uint8_t *buf;
 *     size_t size;
 * } ASN__PRIMITIVE_TYPE_t
 * }
 */
public class ASN__PRIMITIVE_TYPE_t extends ASN__PRIMITIVE_TYPE_s {

    ASN__PRIMITIVE_TYPE_t() {
        // Should not be called directly
    }
}

