// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct asn_dec_rval_s {
 *     enum asn_dec_rval_code_e code;
 *     size_t consumed;
 * } asn_dec_rval_t
 * }
 */
public class asn_dec_rval_t extends asn_dec_rval_s {

    asn_dec_rval_t() {
        // Should not be called directly
    }
}

