// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct asn_bit_data_s {
 *     const uint8_t *buffer;
 *     size_t nboff;
 *     size_t nbits;
 *     size_t moved;
 *     int (*refill)(struct asn_bit_data_s *);
 *     void *refill_key;
 * } asn_bit_data_t
 * }
 */
public class asn_bit_data_t extends asn_bit_data_s {

    asn_bit_data_t() {
        // Should not be called directly
    }
}

