// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct asn_ioc_cell_s {
 *     const char *field_name;
 *     enum {
 *         aioc__undefined = 0,
 *         aioc__value,
 *         aioc__type,
 *         aioc__open_type
 *     } cell_kind;
 *     struct asn_TYPE_descriptor_s *type_descriptor;
 *     const void *value_sptr;
 *     struct {
 *         size_t types_count;
 *         struct {
 *             unsigned int choice_position;
 *         } *types;
 *     } open_type;
 * } asn_ioc_cell_t
 * }
 */
public class asn_ioc_cell_t extends asn_ioc_cell_s {

    asn_ioc_cell_t() {
        // Should not be called directly
    }
}

