// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct AxleWeightLimits {
 *     Int2Unsigned_t maxLadenweightOnAxle1;
 *     Int2Unsigned_t maxLadenweightOnAxle2;
 *     Int2Unsigned_t maxLadenweightOnAxle3;
 *     Int2Unsigned_t maxLadenweightOnAxle4;
 *     Int2Unsigned_t maxLadenweightOnAxle5;
 *     asn_struct_ctx_t _asn_ctx;
 * } AxleWeightLimits_t
 * }
 */
public class AxleWeightLimits_t extends AxleWeightLimits {

    AxleWeightLimits_t() {
        // Should not be called directly
    }
}

