// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct CfgInstantaneousEventTriggers {
 *     CfgInstantaneousEventTriggers_PR present;
 *     union CfgInstantaneousEventTriggers_u {
 *         CfgIntervalEvents_t intervalEvents;
 *         CfgVehicleEvents_t vehicleEvents;
 *         CfgRoadwayEvents_t roadwayEvents;
 *         CfgCommSysPerfEvents_t commSysPerfEvents;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } CfgInstantaneousEventTriggers_t
 * }
 */
public class CfgInstantaneousEventTriggers_t extends CfgInstantaneousEventTriggers {

    CfgInstantaneousEventTriggers_t() {
        // Should not be called directly
    }
}

