// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct CfgStoppedCriteria {
 *     long stoppedSpeedThreshold;
 *     long amountOfTimeBelow;
 *     asn_struct_ctx_t _asn_ctx;
 * } CfgStoppedCriteria_t
 * }
 */
public class CfgStoppedCriteria_t extends CfgStoppedCriteria {

    CfgStoppedCriteria_t() {
        // Should not be called directly
    }
}

