// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct ChargerInfo {
 *     OBJECT_IDENTIFIER_t chargerID;
 *     DescriptiveName_t *descriptiveName;
 *     struct DDateTime *timeStamp;
 *     ChargingConfig_t chargingConfig;
 *     asn_struct_ctx_t _asn_ctx;
 * } ChargerInfo_t
 * }
 */
public class ChargerInfo_t extends ChargerInfo {

    ChargerInfo_t() {
        // Should not be called directly
    }
}

