// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Cinders {
 *     CindersType_t type;
 *     asn_struct_ctx_t _asn_ctx;
 * } Cinders_t
 * }
 */
public class Cinders_t extends Cinders {

    Cinders_t() {
        // Should not be called directly
    }
}

