// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct ClosedNetworkChargesTable {
 *     ClosedNetworkChargesTable_PR present;
 *     union ClosedNetworkChargesTable_u {
 *         EntryChargesTable_t entryChargesTable;
 *         ExitChargesTable_t exitChargesTable;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } ClosedNetworkChargesTable_t
 * }
 */
public class ClosedNetworkChargesTable_t extends ClosedNetworkChargesTable {

    ClosedNetworkChargesTable_t() {
        // Should not be called directly
    }
}

