// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct ComputedLane {
 *     LaneID_t referenceLaneId;
 *     struct ComputedLane__offsetXaxis {
 *         ComputedLane__offsetXaxis_PR present;
 *         union ComputedLane__offsetXaxis_u {
 *             DrivenLineOffsetSm_t small;
 *             DrivenLineOffsetLg_t large;
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } offsetXaxis;
 *     struct ComputedLane__offsetYaxis {
 *         ComputedLane__offsetYaxis_PR present;
 *         union ComputedLane__offsetYaxis_u {
 *             DrivenLineOffsetSm_t small;
 *             DrivenLineOffsetLg_t large;
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } offsetYaxis;
 *     Common_Angle_t *rotateXY;
 *     Scale_B12_t *scaleXaxis;
 *     Scale_B12_t *scaleYaxis;
 *     struct ComputedLane__regional {
 *         struct {
 *             struct Reg_ComputedLane **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_ComputedLane *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } ComputedLane_t
 * }
 */
public class ComputedLane_t extends ComputedLane {

    ComputedLane_t() {
        // Should not be called directly
    }
}

