// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Connection {
 *     ConnectingLane_t connectingLane;
 *     struct IntersectionReferenceID *remoteIntersection;
 *     SignalGroupID_t *signalGroup;
 *     RestrictionClassID_t *userClass;
 *     LaneConnectionID_t *connectionID;
 *     asn_struct_ctx_t _asn_ctx;
 * } Connection_t
 * }
 */
public class Connection_t extends Connection {

    Connection_t() {
        // Should not be called directly
    }
}

