// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct DetectedObjectList {
 *     struct {
 *         struct DetectedObjectData **array;
 *         int count;
 *         int size;
 *         void (*free)(struct DetectedObjectData *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } DetectedObjectList_t
 * }
 */
public class DetectedObjectList_t extends DetectedObjectList {

    DetectedObjectList_t() {
        // Should not be called directly
    }
}

