// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct DriverCharacteristics {
 *     Int1Unsigned_t driverClass;
 *     Int1Unsigned_t tripPurpose;
 *     asn_struct_ctx_t _asn_ctx;
 * } DriverCharacteristics_t
 * }
 */
public class DriverCharacteristics_t extends DriverCharacteristics {

    DriverCharacteristics_t() {
        // Should not be called directly
    }
}

