// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct EventRecurrence {
 *     struct DTime *startTime;
 *     struct DTime *endTime;
 *     struct DDate *startDate;
 *     struct DDate *endDate;
 *     BOOLEAN_t monday;
 *     BOOLEAN_t tuesday;
 *     BOOLEAN_t wednesday;
 *     BOOLEAN_t thursday;
 *     BOOLEAN_t friday;
 *     BOOLEAN_t saturday;
 *     BOOLEAN_t sunday;
 *     BOOLEAN_t *exclusion;
 *     asn_struct_ctx_t _asn_ctx;
 * } EventRecurrence_t
 * }
 */
public class EventRecurrence_t extends EventRecurrence {

    EventRecurrence_t() {
        // Should not be called directly
    }
}

