// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct GeometricProjection {
 *     HeadingSlice_t direction;
 *     Extent_t *extent;
 *     LaneWidth_t *laneWidth;
 *     Circle_t circle;
 *     struct GeometricProjection__regional {
 *         struct {
 *             struct Reg_GeometricProjection **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_GeometricProjection *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } GeometricProjection_t
 * }
 */
public class GeometricProjection_t extends GeometricProjection {

    GeometricProjection_t() {
        // Should not be called directly
    }
}

