// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef BIT_STRING_t GNSSstatus_t
 * }
 */
public class GNSSstatus_t extends BIT_STRING_s {

    GNSSstatus_t() {
        // Should not be called directly
    }
}

