// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct IntersectionState {
 *     DescriptiveName_t *name;
 *     IntersectionReferenceID_t id;
 *     Common_MsgCount_t revision;
 *     IntersectionStatusObject_t status;
 *     MinuteOfTheYear_t *moy;
 *     DSecond_t *timeStamp;
 *     struct EnabledLaneList *enabledLanes;
 *     MovementList_t states;
 *     struct ManeuverAssistList *maneuverAssistList;
 *     struct IntersectionState__regional {
 *         struct {
 *             struct Reg_IntersectionState **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_IntersectionState *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     struct RoadAuthorityID *roadAuthorityID;
 *     asn_struct_ctx_t _asn_ctx;
 * } IntersectionState_t
 * }
 */
public class IntersectionState_t extends IntersectionState {

    IntersectionState_t() {
        // Should not be called directly
    }
}

