// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef BIT_STRING_t LaneAttributes_Striping_t
 * }
 */
public class LaneAttributes_Striping_t extends BIT_STRING_s {

    LaneAttributes_Striping_t() {
        // Should not be called directly
    }
}

