// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct LaneList {
 *     struct {
 *         struct GenericLane **array;
 *         int count;
 *         int size;
 *         void (*free)(struct GenericLane *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } LaneList_t
 * }
 */
public class LaneList_t extends LaneList {

    LaneList_t() {
        // Should not be called directly
    }
}

