// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct MovementEventList {
 *     struct {
 *         struct MovementEvent **array;
 *         int count;
 *         int size;
 *         void (*free)(struct MovementEvent *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } MovementEventList_t
 * }
 */
public class MovementEventList_t extends MovementEventList {

    MovementEventList_t() {
        // Should not be called directly
    }
}

