// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct MovementEvent_addGrpB {
 *     TimeRemaining_t *startTime;
 *     MinTimetoChange_t minEndTime;
 *     MaxTimetoChange_t *maxEndTime;
 *     TimeRemaining_t *likelyTime;
 *     TimeIntervalConfidence_t *confidence;
 *     TimeRemaining_t *nextTime;
 *     asn_struct_ctx_t _asn_ctx;
 * } MovementEvent_addGrpB_t
 * }
 */
public class MovementEvent_addGrpB_t extends MovementEvent_addGrpB {

    MovementEvent_addGrpB_t() {
        // Should not be called directly
    }
}

