// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NMEAcorrections {
 *     MinuteOfTheYear_t *timeStamp;
 *     NMEA_Revision_t *rev;
 *     NMEA_MsgType_t *msg;
 *     ObjectCount_t *wdCount;
 *     NMEA_Payload_t payload;
 *     struct NMEAcorrections__regional {
 *         struct {
 *             struct Reg_NMEAcorrections **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_NMEAcorrections *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } NMEAcorrections_t
 * }
 */
public class NMEAcorrections_t extends NMEAcorrections {

    NMEAcorrections_t() {
        // Should not be called directly
    }
}

