// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Node_LL_44B {
 *     OffsetLL_B22_t lon;
 *     OffsetLL_B22_t lat;
 *     asn_struct_ctx_t _asn_ctx;
 * } Node_LL_44B_t
 * }
 */
public class Node_LL_44B_t extends Node_LL_44B {

    Node_LL_44B_t() {
        // Should not be called directly
    }
}

