// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NodeAttributeSetLL {
 *     struct NodeAttributeLLList *localNode;
 *     struct SegmentAttributeLLList *disabled;
 *     struct SegmentAttributeLLList *enabled;
 *     struct LaneDataAttributeList *data;
 *     Offset_B10_t *dWidth;
 *     Offset_B10_t *dElevation;
 *     struct NodeAttributeSetLL__regional {
 *         struct {
 *             struct Reg_NodeAttributeSetLL **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_NodeAttributeSetLL *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } NodeAttributeSetLL_t
 * }
 */
public class NodeAttributeSetLL_t extends NodeAttributeSetLL {

    NodeAttributeSetLL_t() {
        // Should not be called directly
    }
}

