// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NodeOffsetPointLL {
 *     NodeOffsetPointLL_PR present;
 *     union NodeOffsetPointLL_u {
 *         Node_LL_24B_t node_LL1;
 *         Node_LL_28B_t node_LL2;
 *         Node_LL_32B_t node_LL3;
 *         Node_LL_36B_t node_LL4;
 *         Node_LL_44B_t node_LL5;
 *         Node_LL_48B_t node_LL6;
 *         Node_LLmD_64b_t node_LatLon;
 *         Reg_NodeOffsetPointLL_t regional;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } NodeOffsetPointLL_t
 * }
 */
public class NodeOffsetPointLL_t extends NodeOffsetPointLL {

    NodeOffsetPointLL_t() {
        // Should not be called directly
    }
}

