// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NodeOffsetPointXY_addGrpB {
 *     NodeOffsetPointXY_addGrpB_PR present;
 *     union NodeOffsetPointXY_addGrpB_u {
 *         Node_LLdms_48b_t posA;
 *         Node_LLdms_80b_t posB;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } NodeOffsetPointXY_addGrpB_t
 * }
 */
public class NodeOffsetPointXY_addGrpB_t extends NodeOffsetPointXY_addGrpB {

    NodeOffsetPointXY_addGrpB_t() {
        // Should not be called directly
    }
}

