// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NodeSetLL {
 *     struct {
 *         struct NodeLL **array;
 *         int count;
 *         int size;
 *         void (*free)(struct NodeLL *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } NodeSetLL_t
 * }
 */
public class NodeSetLL_t extends NodeSetLL {

    NodeSetLL_t() {
        // Should not be called directly
    }
}

