// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct NtcipPavement {
 *     NTCIPEssSurfaceTemperature_t *surfaceTemp;
 *     SurfaceTempMeasurementStdDev_t *tempStdDev;
 *     NTCIPPavementSensorSurfaceCondition_t *condition;
 *     NTCIPEssSurfaceIceOrWaterDepth_t *moistureDepth;
 *     struct RoadRoughness *roadRoughness;
 *     asn_struct_ctx_t _asn_ctx;
 * } NtcipPavement_t
 * }
 */
public class NtcipPavement_t extends NtcipPavement {

    NtcipPavement_t() {
        // Should not be called directly
    }
}

