// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct ObstacleSize {
 *     SizeValue_t width;
 *     SizeValue_t length;
 *     SizeValue_t *height;
 *     asn_struct_ctx_t _asn_ctx;
 * } ObstacleSize_t
 * }
 */
public class ObstacleSize_t extends ObstacleSize {

    ObstacleSize_t() {
        // Should not be called directly
    }
}

