// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct PathPrediction {
 *     RadiusOfCurvature_t radiusOfCurve;
 *     Confidence_t confidence;
 *     asn_struct_ctx_t _asn_ctx;
 * } PathPrediction_t
 * }
 */
public class PathPrediction_t extends PathPrediction {

    PathPrediction_t() {
        // Should not be called directly
    }
}

