// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef OCTET_STRING_t Priority_t
 * }
 */
public class Priority_t extends OCTET_STRING {

    Priority_t() {
        // Should not be called directly
    }
}

