// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct ProbeDataManagement {
 *     MinuteOfTheYear_t *timeStamp;
 *     Sample_t sample;
 *     HeadingSlice_t directions;
 *     struct ProbeDataManagement__term {
 *         ProbeDataManagement__term_PR present;
 *         union ProbeDataManagement__term_u {
 *             TermTime_t termtime;
 *             TermDistance_t termDistance;
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } term;
 *     struct ProbeDataManagement__snapshot {
 *         ProbeDataManagement__snapshot_PR present;
 *         union ProbeDataManagement__snapshot_u {
 *             SnapshotTime_t snapshotTime;
 *             SnapshotDistance_t snapshotDistance;
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } snapshot;
 *     SecondOfTime_t txInterval;
 *     struct VehicleStatusRequestList *dataElements;
 *     struct ProbeDataManagement__regional {
 *         struct {
 *             struct Reg_ProbeDataManagement **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_ProbeDataManagement *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * }
 * }
 */
public class ProbeDataManagement {

    ProbeDataManagement() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MessageFrame_h.C_POINTER.withName("timeStamp"),
        Sample.layout().withName("sample"),
        BIT_STRING_s.layout().withName("directions"),
        ProbeDataManagement__term.layout().withName("term"),
        ProbeDataManagement__snapshot.layout().withName("snapshot"),
        MessageFrame_h.C_LONG.withName("txInterval"),
        MessageFrame_h.C_POINTER.withName("dataElements"),
        MessageFrame_h.C_POINTER.withName("regional"),
        asn_struct_ctx_s.layout().withName("_asn_ctx")
    ).withName("ProbeDataManagement");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout timeStamp$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("timeStamp"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * MinuteOfTheYear_t *timeStamp
     * }
     */
    public static final AddressLayout timeStamp$layout() {
        return timeStamp$LAYOUT;
    }

    private static final long timeStamp$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * MinuteOfTheYear_t *timeStamp
     * }
     */
    public static final long timeStamp$offset() {
        return timeStamp$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * MinuteOfTheYear_t *timeStamp
     * }
     */
    public static MemorySegment timeStamp(MemorySegment struct) {
        return struct.get(timeStamp$LAYOUT, timeStamp$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * MinuteOfTheYear_t *timeStamp
     * }
     */
    public static void timeStamp(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(timeStamp$LAYOUT, timeStamp$OFFSET, fieldValue);
    }

    private static final GroupLayout sample$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("sample"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Sample_t sample
     * }
     */
    public static final GroupLayout sample$layout() {
        return sample$LAYOUT;
    }

    private static final long sample$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Sample_t sample
     * }
     */
    public static final long sample$offset() {
        return sample$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Sample_t sample
     * }
     */
    public static MemorySegment sample(MemorySegment struct) {
        return struct.asSlice(sample$OFFSET, sample$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Sample_t sample
     * }
     */
    public static void sample(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, sample$OFFSET, sample$LAYOUT.byteSize());
    }

    private static final GroupLayout directions$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("directions"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * HeadingSlice_t directions
     * }
     */
    public static final GroupLayout directions$layout() {
        return directions$LAYOUT;
    }

    private static final long directions$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * HeadingSlice_t directions
     * }
     */
    public static final long directions$offset() {
        return directions$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * HeadingSlice_t directions
     * }
     */
    public static MemorySegment directions(MemorySegment struct) {
        return struct.asSlice(directions$OFFSET, directions$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * HeadingSlice_t directions
     * }
     */
    public static void directions(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, directions$OFFSET, directions$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * struct ProbeDataManagement__term {
     *     ProbeDataManagement__term_PR present;
     *     union ProbeDataManagement__term_u {
     *         TermTime_t termtime;
     *         TermDistance_t termDistance;
     *     } choice;
     *     asn_struct_ctx_t _asn_ctx;
     * }
     * }
     */
    public static class ProbeDataManagement__term {

        ProbeDataManagement__term() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            MessageFrame_h.C_INT.withName("present"),
            MemoryLayout.paddingLayout(4),
            ProbeDataManagement__term_u.layout().withName("choice"),
            asn_struct_ctx_s.layout().withName("_asn_ctx")
        ).withName("ProbeDataManagement__term");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfInt present$LAYOUT = (OfInt)$LAYOUT.select(groupElement("present"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * ProbeDataManagement__term_PR present
         * }
         */
        public static final OfInt present$layout() {
            return present$LAYOUT;
        }

        private static final long present$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * ProbeDataManagement__term_PR present
         * }
         */
        public static final long present$offset() {
            return present$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * ProbeDataManagement__term_PR present
         * }
         */
        public static int present(MemorySegment struct) {
            return struct.get(present$LAYOUT, present$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * ProbeDataManagement__term_PR present
         * }
         */
        public static void present(MemorySegment struct, int fieldValue) {
            struct.set(present$LAYOUT, present$OFFSET, fieldValue);
        }

        /**
         * {@snippet lang=c :
         * union ProbeDataManagement__term_u {
         *     TermTime_t termtime;
         *     TermDistance_t termDistance;
         * }
         * }
         */
        public static class ProbeDataManagement__term_u {

            ProbeDataManagement__term_u() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
                MessageFrame_h.C_LONG.withName("termtime"),
                MessageFrame_h.C_LONG.withName("termDistance")
            ).withName("ProbeDataManagement__term_u");

            /**
             * The layout of this union
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final OfLong termtime$LAYOUT = (OfLong)$LAYOUT.select(groupElement("termtime"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * TermTime_t termtime
             * }
             */
            public static final OfLong termtime$layout() {
                return termtime$LAYOUT;
            }

            private static final long termtime$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * TermTime_t termtime
             * }
             */
            public static final long termtime$offset() {
                return termtime$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * TermTime_t termtime
             * }
             */
            public static long termtime(MemorySegment union) {
                return union.get(termtime$LAYOUT, termtime$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * TermTime_t termtime
             * }
             */
            public static void termtime(MemorySegment union, long fieldValue) {
                union.set(termtime$LAYOUT, termtime$OFFSET, fieldValue);
            }

            private static final OfLong termDistance$LAYOUT = (OfLong)$LAYOUT.select(groupElement("termDistance"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * TermDistance_t termDistance
             * }
             */
            public static final OfLong termDistance$layout() {
                return termDistance$LAYOUT;
            }

            private static final long termDistance$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * TermDistance_t termDistance
             * }
             */
            public static final long termDistance$offset() {
                return termDistance$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * TermDistance_t termDistance
             * }
             */
            public static long termDistance(MemorySegment union) {
                return union.get(termDistance$LAYOUT, termDistance$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * TermDistance_t termDistance
             * }
             */
            public static void termDistance(MemorySegment union, long fieldValue) {
                union.set(termDistance$LAYOUT, termDistance$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this union
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout choice$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("choice"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__term_u choice
         * }
         */
        public static final GroupLayout choice$layout() {
            return choice$LAYOUT;
        }

        private static final long choice$OFFSET = 8;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__term_u choice
         * }
         */
        public static final long choice$offset() {
            return choice$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__term_u choice
         * }
         */
        public static MemorySegment choice(MemorySegment struct) {
            return struct.asSlice(choice$OFFSET, choice$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__term_u choice
         * }
         */
        public static void choice(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, choice$OFFSET, choice$LAYOUT.byteSize());
        }

        private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final GroupLayout _asn_ctx$layout() {
            return _asn_ctx$LAYOUT;
        }

        private static final long _asn_ctx$OFFSET = 16;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final long _asn_ctx$offset() {
            return _asn_ctx$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static MemorySegment _asn_ctx(MemorySegment struct) {
            return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout term$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("term"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__term term
     * }
     */
    public static final GroupLayout term$layout() {
        return term$LAYOUT;
    }

    private static final long term$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__term term
     * }
     */
    public static final long term$offset() {
        return term$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__term term
     * }
     */
    public static MemorySegment term(MemorySegment struct) {
        return struct.asSlice(term$OFFSET, term$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__term term
     * }
     */
    public static void term(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, term$OFFSET, term$LAYOUT.byteSize());
    }

    /**
     * {@snippet lang=c :
     * struct ProbeDataManagement__snapshot {
     *     ProbeDataManagement__snapshot_PR present;
     *     union ProbeDataManagement__snapshot_u {
     *         SnapshotTime_t snapshotTime;
     *         SnapshotDistance_t snapshotDistance;
     *     } choice;
     *     asn_struct_ctx_t _asn_ctx;
     * }
     * }
     */
    public static class ProbeDataManagement__snapshot {

        ProbeDataManagement__snapshot() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            MessageFrame_h.C_INT.withName("present"),
            MemoryLayout.paddingLayout(4),
            ProbeDataManagement__snapshot_u.layout().withName("choice"),
            asn_struct_ctx_s.layout().withName("_asn_ctx")
        ).withName("ProbeDataManagement__snapshot");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        private static final OfInt present$LAYOUT = (OfInt)$LAYOUT.select(groupElement("present"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * ProbeDataManagement__snapshot_PR present
         * }
         */
        public static final OfInt present$layout() {
            return present$LAYOUT;
        }

        private static final long present$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * ProbeDataManagement__snapshot_PR present
         * }
         */
        public static final long present$offset() {
            return present$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * ProbeDataManagement__snapshot_PR present
         * }
         */
        public static int present(MemorySegment struct) {
            return struct.get(present$LAYOUT, present$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * ProbeDataManagement__snapshot_PR present
         * }
         */
        public static void present(MemorySegment struct, int fieldValue) {
            struct.set(present$LAYOUT, present$OFFSET, fieldValue);
        }

        /**
         * {@snippet lang=c :
         * union ProbeDataManagement__snapshot_u {
         *     SnapshotTime_t snapshotTime;
         *     SnapshotDistance_t snapshotDistance;
         * }
         * }
         */
        public static class ProbeDataManagement__snapshot_u {

            ProbeDataManagement__snapshot_u() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
                SnapshotTime.layout().withName("snapshotTime"),
                SnapshotDistance.layout().withName("snapshotDistance")
            ).withName("ProbeDataManagement__snapshot_u");

            /**
             * The layout of this union
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final GroupLayout snapshotTime$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("snapshotTime"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * SnapshotTime_t snapshotTime
             * }
             */
            public static final GroupLayout snapshotTime$layout() {
                return snapshotTime$LAYOUT;
            }

            private static final long snapshotTime$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * SnapshotTime_t snapshotTime
             * }
             */
            public static final long snapshotTime$offset() {
                return snapshotTime$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * SnapshotTime_t snapshotTime
             * }
             */
            public static MemorySegment snapshotTime(MemorySegment union) {
                return union.asSlice(snapshotTime$OFFSET, snapshotTime$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * SnapshotTime_t snapshotTime
             * }
             */
            public static void snapshotTime(MemorySegment union, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, union, snapshotTime$OFFSET, snapshotTime$LAYOUT.byteSize());
            }

            private static final GroupLayout snapshotDistance$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("snapshotDistance"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * SnapshotDistance_t snapshotDistance
             * }
             */
            public static final GroupLayout snapshotDistance$layout() {
                return snapshotDistance$LAYOUT;
            }

            private static final long snapshotDistance$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * SnapshotDistance_t snapshotDistance
             * }
             */
            public static final long snapshotDistance$offset() {
                return snapshotDistance$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * SnapshotDistance_t snapshotDistance
             * }
             */
            public static MemorySegment snapshotDistance(MemorySegment union) {
                return union.asSlice(snapshotDistance$OFFSET, snapshotDistance$LAYOUT.byteSize());
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * SnapshotDistance_t snapshotDistance
             * }
             */
            public static void snapshotDistance(MemorySegment union, MemorySegment fieldValue) {
                MemorySegment.copy(fieldValue, 0L, union, snapshotDistance$OFFSET, snapshotDistance$LAYOUT.byteSize());
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this union
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout choice$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("choice"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__snapshot_u choice
         * }
         */
        public static final GroupLayout choice$layout() {
            return choice$LAYOUT;
        }

        private static final long choice$OFFSET = 8;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__snapshot_u choice
         * }
         */
        public static final long choice$offset() {
            return choice$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__snapshot_u choice
         * }
         */
        public static MemorySegment choice(MemorySegment struct) {
            return struct.asSlice(choice$OFFSET, choice$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * union ProbeDataManagement__snapshot_u choice
         * }
         */
        public static void choice(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, choice$OFFSET, choice$LAYOUT.byteSize());
        }

        private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final GroupLayout _asn_ctx$layout() {
            return _asn_ctx$LAYOUT;
        }

        private static final long _asn_ctx$OFFSET = 64;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final long _asn_ctx$offset() {
            return _asn_ctx$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static MemorySegment _asn_ctx(MemorySegment struct) {
            return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout snapshot$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("snapshot"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__snapshot snapshot
     * }
     */
    public static final GroupLayout snapshot$layout() {
        return snapshot$LAYOUT;
    }

    private static final long snapshot$OFFSET = 136;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__snapshot snapshot
     * }
     */
    public static final long snapshot$offset() {
        return snapshot$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__snapshot snapshot
     * }
     */
    public static MemorySegment snapshot(MemorySegment struct) {
        return struct.asSlice(snapshot$OFFSET, snapshot$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__snapshot snapshot
     * }
     */
    public static void snapshot(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, snapshot$OFFSET, snapshot$LAYOUT.byteSize());
    }

    private static final OfLong txInterval$LAYOUT = (OfLong)$LAYOUT.select(groupElement("txInterval"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * SecondOfTime_t txInterval
     * }
     */
    public static final OfLong txInterval$layout() {
        return txInterval$LAYOUT;
    }

    private static final long txInterval$OFFSET = 224;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * SecondOfTime_t txInterval
     * }
     */
    public static final long txInterval$offset() {
        return txInterval$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * SecondOfTime_t txInterval
     * }
     */
    public static long txInterval(MemorySegment struct) {
        return struct.get(txInterval$LAYOUT, txInterval$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * SecondOfTime_t txInterval
     * }
     */
    public static void txInterval(MemorySegment struct, long fieldValue) {
        struct.set(txInterval$LAYOUT, txInterval$OFFSET, fieldValue);
    }

    private static final AddressLayout dataElements$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("dataElements"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct VehicleStatusRequestList *dataElements
     * }
     */
    public static final AddressLayout dataElements$layout() {
        return dataElements$LAYOUT;
    }

    private static final long dataElements$OFFSET = 232;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct VehicleStatusRequestList *dataElements
     * }
     */
    public static final long dataElements$offset() {
        return dataElements$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct VehicleStatusRequestList *dataElements
     * }
     */
    public static MemorySegment dataElements(MemorySegment struct) {
        return struct.get(dataElements$LAYOUT, dataElements$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct VehicleStatusRequestList *dataElements
     * }
     */
    public static void dataElements(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(dataElements$LAYOUT, dataElements$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct ProbeDataManagement__regional {
     *     struct {
     *         struct Reg_ProbeDataManagement **array;
     *         int count;
     *         int size;
     *         void (*free)(struct Reg_ProbeDataManagement *);
     *     } list;
     *     asn_struct_ctx_t _asn_ctx;
     * }
     * }
     */
    public static class ProbeDataManagement__regional {

        ProbeDataManagement__regional() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            list.layout().withName("list"),
            asn_struct_ctx_s.layout().withName("_asn_ctx")
        ).withName("ProbeDataManagement__regional");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     struct Reg_ProbeDataManagement **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_ProbeDataManagement *);
         * }
         * }
         */
        public static class list {

            list() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                MessageFrame_h.C_POINTER.withName("array"),
                MessageFrame_h.C_INT.withName("count"),
                MessageFrame_h.C_INT.withName("size"),
                MessageFrame_h.C_POINTER.withName("free")
            ).withName("$anon$76:3");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final AddressLayout array$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("array"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * struct Reg_ProbeDataManagement **array
             * }
             */
            public static final AddressLayout array$layout() {
                return array$LAYOUT;
            }

            private static final long array$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * struct Reg_ProbeDataManagement **array
             * }
             */
            public static final long array$offset() {
                return array$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * struct Reg_ProbeDataManagement **array
             * }
             */
            public static MemorySegment array(MemorySegment struct) {
                return struct.get(array$LAYOUT, array$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * struct Reg_ProbeDataManagement **array
             * }
             */
            public static void array(MemorySegment struct, MemorySegment fieldValue) {
                struct.set(array$LAYOUT, array$OFFSET, fieldValue);
            }

            private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static final OfInt count$layout() {
                return count$LAYOUT;
            }

            private static final long count$OFFSET = 8;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static final long count$offset() {
                return count$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static int count(MemorySegment struct) {
                return struct.get(count$LAYOUT, count$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static void count(MemorySegment struct, int fieldValue) {
                struct.set(count$LAYOUT, count$OFFSET, fieldValue);
            }

            private static final OfInt size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("size"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static final OfInt size$layout() {
                return size$LAYOUT;
            }

            private static final long size$OFFSET = 12;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static final long size$offset() {
                return size$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static int size(MemorySegment struct) {
                return struct.get(size$LAYOUT, size$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static void size(MemorySegment struct, int fieldValue) {
                struct.set(size$LAYOUT, size$OFFSET, fieldValue);
            }

            /**
             * {@snippet lang=c :
             * void (*free)(struct Reg_ProbeDataManagement *)
             * }
             */
            public static class free {

                free() {
                    // Should not be called directly
                }

                /**
                 * The function pointer signature, expressed as a functional interface
                 */
                public interface Function {
                    void apply(MemorySegment _x0);
                }

                private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
                    MessageFrame_h.C_POINTER
                );

                /**
                 * The descriptor of this function pointer
                 */
                public static FunctionDescriptor descriptor() {
                    return $DESC;
                }

                private static final MethodHandle UP$MH = MessageFrame_h.upcallHandle(Function.class, "apply", $DESC);

                /**
                 * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
                 * The lifetime of the returned segment is managed by {@code arena}
                 */
                public static MemorySegment allocate(Function fi, Arena arena) {
                    return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
                }

                private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

                /**
                 * Invoke the upcall stub {@code funcPtr}, with given parameters
                 */
                public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
                    try {
                         DOWN$MH.invokeExact(funcPtr, _x0);
                    } catch (Throwable ex$) {
                        throw new AssertionError("should not reach here", ex$);
                    }
                }
            }

            private static final AddressLayout free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_ProbeDataManagement *)
             * }
             */
            public static final AddressLayout free$layout() {
                return free$LAYOUT;
            }

            private static final long free$OFFSET = 16;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_ProbeDataManagement *)
             * }
             */
            public static final long free$offset() {
                return free$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_ProbeDataManagement *)
             * }
             */
            public static MemorySegment free(MemorySegment struct) {
                return struct.get(free$LAYOUT, free$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_ProbeDataManagement *)
             * }
             */
            public static void free(MemorySegment struct, MemorySegment fieldValue) {
                struct.set(free$LAYOUT, free$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout list$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("list"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_ProbeDataManagement **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_ProbeDataManagement *);
         * } list
         * }
         */
        public static final GroupLayout list$layout() {
            return list$LAYOUT;
        }

        private static final long list$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_ProbeDataManagement **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_ProbeDataManagement *);
         * } list
         * }
         */
        public static final long list$offset() {
            return list$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_ProbeDataManagement **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_ProbeDataManagement *);
         * } list
         * }
         */
        public static MemorySegment list(MemorySegment struct) {
            return struct.asSlice(list$OFFSET, list$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_ProbeDataManagement **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_ProbeDataManagement *);
         * } list
         * }
         */
        public static void list(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, list$OFFSET, list$LAYOUT.byteSize());
        }

        private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final GroupLayout _asn_ctx$layout() {
            return _asn_ctx$LAYOUT;
        }

        private static final long _asn_ctx$OFFSET = 24;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final long _asn_ctx$offset() {
            return _asn_ctx$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static MemorySegment _asn_ctx(MemorySegment struct) {
            return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final AddressLayout regional$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("regional"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__regional *regional
     * }
     */
    public static final AddressLayout regional$layout() {
        return regional$LAYOUT;
    }

    private static final long regional$OFFSET = 240;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__regional *regional
     * }
     */
    public static final long regional$offset() {
        return regional$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__regional *regional
     * }
     */
    public static MemorySegment regional(MemorySegment struct) {
        return struct.get(regional$LAYOUT, regional$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ProbeDataManagement__regional *regional
     * }
     */
    public static void regional(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(regional$LAYOUT, regional$OFFSET, fieldValue);
    }

    private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final GroupLayout _asn_ctx$layout() {
        return _asn_ctx$LAYOUT;
    }

    private static final long _asn_ctx$OFFSET = 248;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final long _asn_ctx$offset() {
        return _asn_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static MemorySegment _asn_ctx(MemorySegment struct) {
        return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

