// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct PropelledInformation {
 *     PropelledInformation_PR present;
 *     union PropelledInformation_u {
 *         HumanPropelledType_t human;
 *         AnimalPropelledType_t animal;
 *         MotorizedPropelledType_t motor;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } PropelledInformation_t
 * }
 */
public class PropelledInformation_t extends PropelledInformation {

    PropelledInformation_t() {
        // Should not be called directly
    }
}

