// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef BIT_STRING_t PublicSafetyAndRoadWorkerActivity_t
 * }
 */
public class PublicSafetyAndRoadWorkerActivity_t extends BIT_STRING_s {

    PublicSafetyAndRoadWorkerActivity_t() {
        // Should not be called directly
    }
}

