// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Reg_NodeAttributeSetXY {
 *     RegionId_t regionId;
 *     struct Reg_NodeAttributeSetXY__regExtValue {
 *         Reg_NodeAttributeSetXY__regExtValue_PR present;
 *         union Reg_NodeAttributeSetXY__regExtValue_u {
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } regExtValue;
 *     asn_struct_ctx_t _asn_ctx;
 * } Reg_NodeAttributeSetXY_t
 * }
 */
public class Reg_NodeAttributeSetXY_t extends Reg_NodeAttributeSetXY {

    Reg_NodeAttributeSetXY_t() {
        // Should not be called directly
    }
}

