// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Reg_NodeAttributeSetLL {
 *     RegionId_t regionId;
 *     struct Reg_NodeAttributeSetLL__regExtValue {
 *         Reg_NodeAttributeSetLL__regExtValue_PR present;
 *         union Reg_NodeAttributeSetLL__regExtValue_u {
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } regExtValue;
 *     asn_struct_ctx_t _asn_ctx;
 * } Reg_NodeAttributeSetLL_t
 * }
 */
public class Reg_NodeAttributeSetLL_t extends Reg_NodeAttributeSetLL {

    Reg_NodeAttributeSetLL_t() {
        // Should not be called directly
    }
}

