// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Reg_TestMessage12 {
 *     RegionId_t regionId;
 *     struct Reg_TestMessage12__regExtValue {
 *         Reg_TestMessage12__regExtValue_PR present;
 *         union Reg_TestMessage12__regExtValue_u {
 *         } choice;
 *         asn_struct_ctx_t _asn_ctx;
 *     } regExtValue;
 *     asn_struct_ctx_t _asn_ctx;
 * } Reg_TestMessage12_t
 * }
 */
public class Reg_TestMessage12_t extends Reg_TestMessage12 {

    Reg_TestMessage12_t() {
        // Should not be called directly
    }
}

