// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RegulatorySpeedLimit {
 *     SpeedLimitType_t type;
 *     Velocity_t speed;
 *     asn_struct_ctx_t _asn_ctx;
 * } RegulatorySpeedLimit_t
 * }
 */
public class RegulatorySpeedLimit_t extends RegulatorySpeedLimit {

    RegulatorySpeedLimit_t() {
        // Should not be called directly
    }
}

