// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RoadUserChargingConfigMessage {
 *     struct RoadUserChargingConfigMessage__chargerInfoTable {
 *         struct {
 *             struct ChargerInfo **array;
 *             int count;
 *             int size;
 *             void (*free)(struct ChargerInfo *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } chargerInfoTable;
 *     asn_struct_ctx_t _asn_ctx;
 * } RoadUserChargingConfigMessage_t
 * }
 */
public class RoadUserChargingConfigMessage_t extends RoadUserChargingConfigMessage {

    RoadUserChargingConfigMessage_t() {
        // Should not be called directly
    }
}

