// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RoadWeatherDownload {
 *     TravelerDataFrameList_t travelerData;
 *     struct WDMSFleetData *wdmsFleetData;
 *     asn_struct_ctx_t _asn_ctx;
 * } RoadWeatherDownload_t
 * }
 */
public class RoadWeatherDownload_t extends RoadWeatherDownload {

    RoadWeatherDownload_t() {
        // Should not be called directly
    }
}

