// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RptDevType {
 *     BOOLEAN_t oemOrAftermarket;
 *     BOOLEAN_t canOrIvnConnected;
 *     BOOLEAN_t *mcoCapable;
 *     asn_struct_ctx_t _asn_ctx;
 * } RptDevType_t
 * }
 */
public class RptDevType_t extends RptDevType {

    RptDevType_t() {
        // Should not be called directly
    }
}

