// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RptTrafficMetrics {
 *     RptTrafficMetrics_PR present;
 *     union RptTrafficMetrics_u {
 *         NULL_t trfsigApproachDelay;
 *         NULL_t trfsigApproachSpeed;
 *         NULL_t trfsigArrivalGreen;
 *         NULL_t trfsigArrivalRed;
 *         NULL_t trfsigPedDelay;
 *         NULL_t trfsigSpatMismatch;
 *         NULL_t trfsigSpatTimingError;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } RptTrafficMetrics_t
 * }
 */
public class RptTrafficMetrics_t extends RptTrafficMetrics {

    RptTrafficMetrics_t() {
        // Should not be called directly
    }
}

