// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RptVehicleEvents {
 *     RptVehicleEvents_PR present;
 *     union RptVehicleEvents_u {
 *         NULL_t headLights;
 *         NULL_t fogLights;
 *         NULL_t hazardLights;
 *         RptKinematicEvents_t kinematicEvents;
 *         NULL_t wiperStatusChange;
 *         NULL_t lowSpeed;
 *         NULL_t resumedSpeed;
 *         NULL_t vehEntrsExitsRegion;
 *         NULL_t emerVehDetect;
 *         NULL_t emerVehLightBar;
 *         NULL_t reqTspEvp;
 *         NULL_t transitVehPassCnt;
 *         NULL_t transitVehDoor;
 *         NULL_t v2xMsgRecption;
 *         RptDriverAlertsAndWarnings_t driverAlertsAndWarnings;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } RptVehicleEvents_t
 * }
 */
public class RptVehicleEvents_t extends RptVehicleEvents {

    RptVehicleEvents_t() {
        // Should not be called directly
    }
}

