// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct RTCMmessageList {
 *     struct {
 *         RTCMmessage_t **array;
 *         int count;
 *         int size;
 *         void (*free)(RTCMmessage_t *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } RTCMmessageList_t
 * }
 */
public class RTCMmessageList_t extends RTCMmessageList {

    RTCMmessageList_t() {
        // Should not be called directly
    }
}

