// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SchoolBusJ2945Slash1C {
 *     BOOLEAN_t flashingAmberLights;
 *     BOOLEAN_t flashingRedLights;
 *     BOOLEAN_t *studentsCrossingFront;
 *     BOOLEAN_t *studentsCrossingBehind;
 *     BOOLEAN_t *studentsLoading;
 *     BOOLEAN_t *studentsUnloading;
 *     BOOLEAN_t *wheelchairLiftInUse;
 *     BOOLEAN_t *emergencyExitOpen;
 *     BOOLEAN_t *emergencyRequestMedical;
 *     BOOLEAN_t *emergencyRequestFire;
 *     BOOLEAN_t *emergencyRequestPolice;
 *     asn_struct_ctx_t _asn_ctx;
 * } SchoolBusJ2945Slash1C_t
 * }
 */
public class SchoolBusJ2945Slash1C_t extends SchoolBusJ2945Slash1C {

    SchoolBusJ2945Slash1C_t() {
        // Should not be called directly
    }
}

