// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct ShapePointSet {
 *     struct Position3D *anchor;
 *     LaneWidth_t *laneWidth;
 *     DirectionOfUse_t *directionality;
 *     NodeListXY_t nodeList;
 *     asn_struct_ctx_t _asn_ctx;
 * } ShapePointSet_t
 * }
 */
public class ShapePointSet_t extends ShapePointSet {

    ShapePointSet_t() {
        // Should not be called directly
    }
}

