// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SignalStatusList {
 *     struct {
 *         struct SignalStatus **array;
 *         int count;
 *         int size;
 *         void (*free)(struct SignalStatus *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } SignalStatusList_t
 * }
 */
public class SignalStatusList_t extends SignalStatusList {

    SignalStatusList_t() {
        // Should not be called directly
    }
}

