// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SignalRequest {
 *     IntersectionReferenceID_t id;
 *     RequestID_t requestID;
 *     PriorityRequestType_t requestType;
 *     IntersectionAccessPoint_t inBoundLane;
 *     struct IntersectionAccessPoint *outBoundLane;
 *     struct SignalRequest__regional {
 *         struct {
 *             struct Reg_SignalRequest **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_SignalRequest *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } SignalRequest_t
 * }
 */
public class SignalRequest_t extends SignalRequest {

    SignalRequest_t() {
        // Should not be called directly
    }
}

