// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SignalControlZone {
 *     Reg_SignalControlZone_t zone;
 *     asn_struct_ctx_t _asn_ctx;
 * } SignalControlZone_t
 * }
 */
public class SignalControlZone_t extends SignalControlZone {

    SignalControlZone_t() {
        // Should not be called directly
    }
}

