// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct Snow {
 *     SnowType_t type;
 *     asn_struct_ctx_t _asn_ctx;
 * } Snow_t
 * }
 */
public class Snow_t extends Snow {

    Snow_t() {
        // Should not be called directly
    }
}

