// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SpecialVehicleExtensions {
 *     struct EmergencyDetails *vehicleAlerts;
 *     struct EventDescription *description;
 *     struct TrailerData *doNotUse;
 *     asn_struct_ctx_t _asn_ctx;
 * } SpecialVehicleExtensions_t
 * }
 */
public class SpecialVehicleExtensions_t extends SpecialVehicleExtensions {

    SpecialVehicleExtensions_t() {
        // Should not be called directly
    }
}

