// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct SubManeuver {
 *     TemporaryID_t executantVehID;
 *     TemporaryIDPointer_t affectedVehIDs;
 *     CurrentStateData_t currentStateData;
 *     struct TargetRoadResource *targetRoadResource;
 *     DDateTime_t startTime;
 *     DDateTime_t endTime;
 *     Speed_t *minSpeed;
 *     Speed_t *maxSpeed;
 *     asn_struct_ctx_t _asn_ctx;
 * } SubManeuver_t
 * }
 */
public class SubManeuver_t extends SubManeuver {

    SubManeuver_t() {
        // Should not be called directly
    }
}

