// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct SupplementalVehicleExtensions {
 *     BasicVehicleClass_t *classification;
 *     struct VehicleClassification *classDetails;
 *     struct VehicleData *vehicleData;
 *     struct WeatherReport *doNotUse1;
 *     struct WeatherProbe *doNotUse2;
 *     struct ObstacleDetection *doNotUse3;
 *     struct DisabledVehicle *status;
 *     struct SpeedProfile *doNotUse4;
 *     struct RTCMPackage *doNotUse5;
 *     struct SupplementalVehicleExtensions__regional {
 *         struct {
 *             struct Reg_SupplementalVehicleExtensions **array;
 *             int count;
 *             int size;
 *             void (*free)(struct Reg_SupplementalVehicleExtensions *);
 *         } list;
 *         asn_struct_ctx_t _asn_ctx;
 *     } *regional;
 *     RptVehicleClass_t *fhwaVehicleClass;
 *     struct TrailersJ2945Slash1B *trailers;
 *     struct SchoolBusJ2945Slash1C *schoolBus;
 *     asn_struct_ctx_t _asn_ctx;
 * }
 * }
 */
public class SupplementalVehicleExtensions {

    SupplementalVehicleExtensions() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MessageFrame_h.C_POINTER.withName("classification"),
        MessageFrame_h.C_POINTER.withName("classDetails"),
        MessageFrame_h.C_POINTER.withName("vehicleData"),
        MessageFrame_h.C_POINTER.withName("doNotUse1"),
        MessageFrame_h.C_POINTER.withName("doNotUse2"),
        MessageFrame_h.C_POINTER.withName("doNotUse3"),
        MessageFrame_h.C_POINTER.withName("status"),
        MessageFrame_h.C_POINTER.withName("doNotUse4"),
        MessageFrame_h.C_POINTER.withName("doNotUse5"),
        MessageFrame_h.C_POINTER.withName("regional"),
        MessageFrame_h.C_POINTER.withName("fhwaVehicleClass"),
        MessageFrame_h.C_POINTER.withName("trailers"),
        MessageFrame_h.C_POINTER.withName("schoolBus"),
        asn_struct_ctx_s.layout().withName("_asn_ctx")
    ).withName("SupplementalVehicleExtensions");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout classification$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("classification"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * BasicVehicleClass_t *classification
     * }
     */
    public static final AddressLayout classification$layout() {
        return classification$LAYOUT;
    }

    private static final long classification$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * BasicVehicleClass_t *classification
     * }
     */
    public static final long classification$offset() {
        return classification$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * BasicVehicleClass_t *classification
     * }
     */
    public static MemorySegment classification(MemorySegment struct) {
        return struct.get(classification$LAYOUT, classification$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * BasicVehicleClass_t *classification
     * }
     */
    public static void classification(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(classification$LAYOUT, classification$OFFSET, fieldValue);
    }

    private static final AddressLayout classDetails$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("classDetails"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct VehicleClassification *classDetails
     * }
     */
    public static final AddressLayout classDetails$layout() {
        return classDetails$LAYOUT;
    }

    private static final long classDetails$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct VehicleClassification *classDetails
     * }
     */
    public static final long classDetails$offset() {
        return classDetails$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct VehicleClassification *classDetails
     * }
     */
    public static MemorySegment classDetails(MemorySegment struct) {
        return struct.get(classDetails$LAYOUT, classDetails$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct VehicleClassification *classDetails
     * }
     */
    public static void classDetails(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(classDetails$LAYOUT, classDetails$OFFSET, fieldValue);
    }

    private static final AddressLayout vehicleData$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("vehicleData"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct VehicleData *vehicleData
     * }
     */
    public static final AddressLayout vehicleData$layout() {
        return vehicleData$LAYOUT;
    }

    private static final long vehicleData$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct VehicleData *vehicleData
     * }
     */
    public static final long vehicleData$offset() {
        return vehicleData$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct VehicleData *vehicleData
     * }
     */
    public static MemorySegment vehicleData(MemorySegment struct) {
        return struct.get(vehicleData$LAYOUT, vehicleData$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct VehicleData *vehicleData
     * }
     */
    public static void vehicleData(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(vehicleData$LAYOUT, vehicleData$OFFSET, fieldValue);
    }

    private static final AddressLayout doNotUse1$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("doNotUse1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct WeatherReport *doNotUse1
     * }
     */
    public static final AddressLayout doNotUse1$layout() {
        return doNotUse1$LAYOUT;
    }

    private static final long doNotUse1$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct WeatherReport *doNotUse1
     * }
     */
    public static final long doNotUse1$offset() {
        return doNotUse1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct WeatherReport *doNotUse1
     * }
     */
    public static MemorySegment doNotUse1(MemorySegment struct) {
        return struct.get(doNotUse1$LAYOUT, doNotUse1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct WeatherReport *doNotUse1
     * }
     */
    public static void doNotUse1(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(doNotUse1$LAYOUT, doNotUse1$OFFSET, fieldValue);
    }

    private static final AddressLayout doNotUse2$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("doNotUse2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct WeatherProbe *doNotUse2
     * }
     */
    public static final AddressLayout doNotUse2$layout() {
        return doNotUse2$LAYOUT;
    }

    private static final long doNotUse2$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct WeatherProbe *doNotUse2
     * }
     */
    public static final long doNotUse2$offset() {
        return doNotUse2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct WeatherProbe *doNotUse2
     * }
     */
    public static MemorySegment doNotUse2(MemorySegment struct) {
        return struct.get(doNotUse2$LAYOUT, doNotUse2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct WeatherProbe *doNotUse2
     * }
     */
    public static void doNotUse2(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(doNotUse2$LAYOUT, doNotUse2$OFFSET, fieldValue);
    }

    private static final AddressLayout doNotUse3$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("doNotUse3"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct ObstacleDetection *doNotUse3
     * }
     */
    public static final AddressLayout doNotUse3$layout() {
        return doNotUse3$LAYOUT;
    }

    private static final long doNotUse3$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct ObstacleDetection *doNotUse3
     * }
     */
    public static final long doNotUse3$offset() {
        return doNotUse3$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct ObstacleDetection *doNotUse3
     * }
     */
    public static MemorySegment doNotUse3(MemorySegment struct) {
        return struct.get(doNotUse3$LAYOUT, doNotUse3$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct ObstacleDetection *doNotUse3
     * }
     */
    public static void doNotUse3(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(doNotUse3$LAYOUT, doNotUse3$OFFSET, fieldValue);
    }

    private static final AddressLayout status$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct DisabledVehicle *status
     * }
     */
    public static final AddressLayout status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct DisabledVehicle *status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct DisabledVehicle *status
     * }
     */
    public static MemorySegment status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct DisabledVehicle *status
     * }
     */
    public static void status(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final AddressLayout doNotUse4$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("doNotUse4"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct SpeedProfile *doNotUse4
     * }
     */
    public static final AddressLayout doNotUse4$layout() {
        return doNotUse4$LAYOUT;
    }

    private static final long doNotUse4$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct SpeedProfile *doNotUse4
     * }
     */
    public static final long doNotUse4$offset() {
        return doNotUse4$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct SpeedProfile *doNotUse4
     * }
     */
    public static MemorySegment doNotUse4(MemorySegment struct) {
        return struct.get(doNotUse4$LAYOUT, doNotUse4$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct SpeedProfile *doNotUse4
     * }
     */
    public static void doNotUse4(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(doNotUse4$LAYOUT, doNotUse4$OFFSET, fieldValue);
    }

    private static final AddressLayout doNotUse5$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("doNotUse5"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct RTCMPackage *doNotUse5
     * }
     */
    public static final AddressLayout doNotUse5$layout() {
        return doNotUse5$LAYOUT;
    }

    private static final long doNotUse5$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct RTCMPackage *doNotUse5
     * }
     */
    public static final long doNotUse5$offset() {
        return doNotUse5$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct RTCMPackage *doNotUse5
     * }
     */
    public static MemorySegment doNotUse5(MemorySegment struct) {
        return struct.get(doNotUse5$LAYOUT, doNotUse5$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct RTCMPackage *doNotUse5
     * }
     */
    public static void doNotUse5(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(doNotUse5$LAYOUT, doNotUse5$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * struct SupplementalVehicleExtensions__regional {
     *     struct {
     *         struct Reg_SupplementalVehicleExtensions **array;
     *         int count;
     *         int size;
     *         void (*free)(struct Reg_SupplementalVehicleExtensions *);
     *     } list;
     *     asn_struct_ctx_t _asn_ctx;
     * }
     * }
     */
    public static class SupplementalVehicleExtensions__regional {

        SupplementalVehicleExtensions__regional() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
            list.layout().withName("list"),
            asn_struct_ctx_s.layout().withName("_asn_ctx")
        ).withName("SupplementalVehicleExtensions__regional");

        /**
         * The layout of this struct
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * struct {
         *     struct Reg_SupplementalVehicleExtensions **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_SupplementalVehicleExtensions *);
         * }
         * }
         */
        public static class list {

            list() {
                // Should not be called directly
            }

            private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
                MessageFrame_h.C_POINTER.withName("array"),
                MessageFrame_h.C_INT.withName("count"),
                MessageFrame_h.C_INT.withName("size"),
                MessageFrame_h.C_POINTER.withName("free")
            ).withName("$anon$50:3");

            /**
             * The layout of this struct
             */
            public static final GroupLayout layout() {
                return $LAYOUT;
            }

            private static final AddressLayout array$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("array"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * struct Reg_SupplementalVehicleExtensions **array
             * }
             */
            public static final AddressLayout array$layout() {
                return array$LAYOUT;
            }

            private static final long array$OFFSET = 0;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * struct Reg_SupplementalVehicleExtensions **array
             * }
             */
            public static final long array$offset() {
                return array$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * struct Reg_SupplementalVehicleExtensions **array
             * }
             */
            public static MemorySegment array(MemorySegment struct) {
                return struct.get(array$LAYOUT, array$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * struct Reg_SupplementalVehicleExtensions **array
             * }
             */
            public static void array(MemorySegment struct, MemorySegment fieldValue) {
                struct.set(array$LAYOUT, array$OFFSET, fieldValue);
            }

            private static final OfInt count$LAYOUT = (OfInt)$LAYOUT.select(groupElement("count"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static final OfInt count$layout() {
                return count$LAYOUT;
            }

            private static final long count$OFFSET = 8;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static final long count$offset() {
                return count$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static int count(MemorySegment struct) {
                return struct.get(count$LAYOUT, count$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * int count
             * }
             */
            public static void count(MemorySegment struct, int fieldValue) {
                struct.set(count$LAYOUT, count$OFFSET, fieldValue);
            }

            private static final OfInt size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("size"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static final OfInt size$layout() {
                return size$LAYOUT;
            }

            private static final long size$OFFSET = 12;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static final long size$offset() {
                return size$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static int size(MemorySegment struct) {
                return struct.get(size$LAYOUT, size$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * int size
             * }
             */
            public static void size(MemorySegment struct, int fieldValue) {
                struct.set(size$LAYOUT, size$OFFSET, fieldValue);
            }

            /**
             * {@snippet lang=c :
             * void (*free)(struct Reg_SupplementalVehicleExtensions *)
             * }
             */
            public static class free {

                free() {
                    // Should not be called directly
                }

                /**
                 * The function pointer signature, expressed as a functional interface
                 */
                public interface Function {
                    void apply(MemorySegment _x0);
                }

                private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
                    MessageFrame_h.C_POINTER
                );

                /**
                 * The descriptor of this function pointer
                 */
                public static FunctionDescriptor descriptor() {
                    return $DESC;
                }

                private static final MethodHandle UP$MH = MessageFrame_h.upcallHandle(Function.class, "apply", $DESC);

                /**
                 * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
                 * The lifetime of the returned segment is managed by {@code arena}
                 */
                public static MemorySegment allocate(Function fi, Arena arena) {
                    return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
                }

                private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

                /**
                 * Invoke the upcall stub {@code funcPtr}, with given parameters
                 */
                public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
                    try {
                         DOWN$MH.invokeExact(funcPtr, _x0);
                    } catch (Throwable ex$) {
                        throw new AssertionError("should not reach here", ex$);
                    }
                }
            }

            private static final AddressLayout free$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("free"));

            /**
             * Layout for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_SupplementalVehicleExtensions *)
             * }
             */
            public static final AddressLayout free$layout() {
                return free$LAYOUT;
            }

            private static final long free$OFFSET = 16;

            /**
             * Offset for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_SupplementalVehicleExtensions *)
             * }
             */
            public static final long free$offset() {
                return free$OFFSET;
            }

            /**
             * Getter for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_SupplementalVehicleExtensions *)
             * }
             */
            public static MemorySegment free(MemorySegment struct) {
                return struct.get(free$LAYOUT, free$OFFSET);
            }

            /**
             * Setter for field:
             * {@snippet lang=c :
             * void (*free)(struct Reg_SupplementalVehicleExtensions *)
             * }
             */
            public static void free(MemorySegment struct, MemorySegment fieldValue) {
                struct.set(free$LAYOUT, free$OFFSET, fieldValue);
            }

            /**
             * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
             * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
             */
            public static MemorySegment asSlice(MemorySegment array, long index) {
                return array.asSlice(layout().byteSize() * index);
            }

            /**
             * The size (in bytes) of this struct
             */
            public static long sizeof() { return layout().byteSize(); }

            /**
             * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
             */
            public static MemorySegment allocate(SegmentAllocator allocator) {
                return allocator.allocate(layout());
            }

            /**
             * Allocate an array of size {@code elementCount} using {@code allocator}.
             * The returned segment has size {@code elementCount * layout().byteSize()}.
             */
            public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
                return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
                return reinterpret(addr, 1, arena, cleanup);
            }

            /**
             * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
             * The returned segment has size {@code elementCount * layout().byteSize()}
             */
            public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
                return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
            }
        }

        private static final GroupLayout list$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("list"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_SupplementalVehicleExtensions **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_SupplementalVehicleExtensions *);
         * } list
         * }
         */
        public static final GroupLayout list$layout() {
            return list$LAYOUT;
        }

        private static final long list$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_SupplementalVehicleExtensions **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_SupplementalVehicleExtensions *);
         * } list
         * }
         */
        public static final long list$offset() {
            return list$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_SupplementalVehicleExtensions **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_SupplementalVehicleExtensions *);
         * } list
         * }
         */
        public static MemorySegment list(MemorySegment struct) {
            return struct.asSlice(list$OFFSET, list$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * struct {
         *     struct Reg_SupplementalVehicleExtensions **array;
         *     int count;
         *     int size;
         *     void (*free)(struct Reg_SupplementalVehicleExtensions *);
         * } list
         * }
         */
        public static void list(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, list$OFFSET, list$LAYOUT.byteSize());
        }

        private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final GroupLayout _asn_ctx$layout() {
            return _asn_ctx$LAYOUT;
        }

        private static final long _asn_ctx$OFFSET = 24;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static final long _asn_ctx$offset() {
            return _asn_ctx$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static MemorySegment _asn_ctx(MemorySegment struct) {
            return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * asn_struct_ctx_t _asn_ctx
         * }
         */
        public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
            MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this struct
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final AddressLayout regional$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("regional"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct SupplementalVehicleExtensions__regional *regional
     * }
     */
    public static final AddressLayout regional$layout() {
        return regional$LAYOUT;
    }

    private static final long regional$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct SupplementalVehicleExtensions__regional *regional
     * }
     */
    public static final long regional$offset() {
        return regional$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct SupplementalVehicleExtensions__regional *regional
     * }
     */
    public static MemorySegment regional(MemorySegment struct) {
        return struct.get(regional$LAYOUT, regional$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct SupplementalVehicleExtensions__regional *regional
     * }
     */
    public static void regional(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(regional$LAYOUT, regional$OFFSET, fieldValue);
    }

    private static final AddressLayout fhwaVehicleClass$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fhwaVehicleClass"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * RptVehicleClass_t *fhwaVehicleClass
     * }
     */
    public static final AddressLayout fhwaVehicleClass$layout() {
        return fhwaVehicleClass$LAYOUT;
    }

    private static final long fhwaVehicleClass$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * RptVehicleClass_t *fhwaVehicleClass
     * }
     */
    public static final long fhwaVehicleClass$offset() {
        return fhwaVehicleClass$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * RptVehicleClass_t *fhwaVehicleClass
     * }
     */
    public static MemorySegment fhwaVehicleClass(MemorySegment struct) {
        return struct.get(fhwaVehicleClass$LAYOUT, fhwaVehicleClass$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * RptVehicleClass_t *fhwaVehicleClass
     * }
     */
    public static void fhwaVehicleClass(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fhwaVehicleClass$LAYOUT, fhwaVehicleClass$OFFSET, fieldValue);
    }

    private static final AddressLayout trailers$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("trailers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct TrailersJ2945Slash1B *trailers
     * }
     */
    public static final AddressLayout trailers$layout() {
        return trailers$LAYOUT;
    }

    private static final long trailers$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct TrailersJ2945Slash1B *trailers
     * }
     */
    public static final long trailers$offset() {
        return trailers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct TrailersJ2945Slash1B *trailers
     * }
     */
    public static MemorySegment trailers(MemorySegment struct) {
        return struct.get(trailers$LAYOUT, trailers$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct TrailersJ2945Slash1B *trailers
     * }
     */
    public static void trailers(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(trailers$LAYOUT, trailers$OFFSET, fieldValue);
    }

    private static final AddressLayout schoolBus$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("schoolBus"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct SchoolBusJ2945Slash1C *schoolBus
     * }
     */
    public static final AddressLayout schoolBus$layout() {
        return schoolBus$LAYOUT;
    }

    private static final long schoolBus$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct SchoolBusJ2945Slash1C *schoolBus
     * }
     */
    public static final long schoolBus$offset() {
        return schoolBus$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct SchoolBusJ2945Slash1C *schoolBus
     * }
     */
    public static MemorySegment schoolBus(MemorySegment struct) {
        return struct.get(schoolBus$LAYOUT, schoolBus$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct SchoolBusJ2945Slash1C *schoolBus
     * }
     */
    public static void schoolBus(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(schoolBus$LAYOUT, schoolBus$OFFSET, fieldValue);
    }

    private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final GroupLayout _asn_ctx$layout() {
        return _asn_ctx$LAYOUT;
    }

    private static final long _asn_ctx$OFFSET = 104;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final long _asn_ctx$offset() {
        return _asn_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static MemorySegment _asn_ctx(MemorySegment struct) {
        return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

