// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct TestMessage13 {
 *     struct Header *header;
 *     struct Reg_TestMessage13 *regional;
 *     asn_struct_ctx_t _asn_ctx;
 * } TestMessage13_t
 * }
 */
public class TestMessage13_t extends TestMessage13 {

    TestMessage13_t() {
        // Should not be called directly
    }
}

