// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef BIT_STRING_t TrafficLightControllerStatus_t
 * }
 */
public class TrafficLightControllerStatus_t extends BIT_STRING_s {

    TrafficLightControllerStatus_t() {
        // Should not be called directly
    }
}

