// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct TrailerUnitDescriptionList {
 *     struct {
 *         struct TrailerUnitDescription **array;
 *         int count;
 *         int size;
 *         void (*free)(struct TrailerUnitDescription *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } TrailerUnitDescriptionList_t
 * }
 */
public class TrailerUnitDescriptionList_t extends TrailerUnitDescriptionList {

    TrailerUnitDescriptionList_t() {
        // Should not be called directly
    }
}

