// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct TRRLocationType3 {
 *     struct {
 *         struct PositionOffsetXYZ **array;
 *         int count;
 *         int size;
 *         void (*free)(struct PositionOffsetXYZ *);
 *     } list;
 *     asn_struct_ctx_t _asn_ctx;
 * } TRRLocationType3_t
 * }
 */
public class TRRLocationType3_t extends TRRLocationType3 {

    TRRLocationType3_t() {
        // Should not be called directly
    }
}

