// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct TumAckHash {
 *     OCTET_STRING_t *signedTumHash;
 *     TemporaryID_t tempId;
 *     Common_MsgCount_t tumSequenceNum;
 *     asn_struct_ctx_t _asn_ctx;
 * }
 * }
 */
public class TumAckHash {

    TumAckHash() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MessageFrame_h.C_POINTER.withName("signedTumHash"),
        OCTET_STRING.layout().withName("tempId"),
        MessageFrame_h.C_LONG.withName("tumSequenceNum"),
        asn_struct_ctx_s.layout().withName("_asn_ctx")
    ).withName("TumAckHash");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout signedTumHash$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("signedTumHash"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OCTET_STRING_t *signedTumHash
     * }
     */
    public static final AddressLayout signedTumHash$layout() {
        return signedTumHash$LAYOUT;
    }

    private static final long signedTumHash$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OCTET_STRING_t *signedTumHash
     * }
     */
    public static final long signedTumHash$offset() {
        return signedTumHash$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OCTET_STRING_t *signedTumHash
     * }
     */
    public static MemorySegment signedTumHash(MemorySegment struct) {
        return struct.get(signedTumHash$LAYOUT, signedTumHash$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OCTET_STRING_t *signedTumHash
     * }
     */
    public static void signedTumHash(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(signedTumHash$LAYOUT, signedTumHash$OFFSET, fieldValue);
    }

    private static final GroupLayout tempId$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("tempId"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * TemporaryID_t tempId
     * }
     */
    public static final GroupLayout tempId$layout() {
        return tempId$LAYOUT;
    }

    private static final long tempId$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * TemporaryID_t tempId
     * }
     */
    public static final long tempId$offset() {
        return tempId$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * TemporaryID_t tempId
     * }
     */
    public static MemorySegment tempId(MemorySegment struct) {
        return struct.asSlice(tempId$OFFSET, tempId$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * TemporaryID_t tempId
     * }
     */
    public static void tempId(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, tempId$OFFSET, tempId$LAYOUT.byteSize());
    }

    private static final OfLong tumSequenceNum$LAYOUT = (OfLong)$LAYOUT.select(groupElement("tumSequenceNum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Common_MsgCount_t tumSequenceNum
     * }
     */
    public static final OfLong tumSequenceNum$layout() {
        return tumSequenceNum$LAYOUT;
    }

    private static final long tumSequenceNum$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Common_MsgCount_t tumSequenceNum
     * }
     */
    public static final long tumSequenceNum$offset() {
        return tumSequenceNum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Common_MsgCount_t tumSequenceNum
     * }
     */
    public static long tumSequenceNum(MemorySegment struct) {
        return struct.get(tumSequenceNum$LAYOUT, tumSequenceNum$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Common_MsgCount_t tumSequenceNum
     * }
     */
    public static void tumSequenceNum(MemorySegment struct, long fieldValue) {
        struct.set(tumSequenceNum$LAYOUT, tumSequenceNum$OFFSET, fieldValue);
    }

    private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final GroupLayout _asn_ctx$layout() {
        return _asn_ctx$LAYOUT;
    }

    private static final long _asn_ctx$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final long _asn_ctx$offset() {
        return _asn_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static MemorySegment _asn_ctx(MemorySegment struct) {
        return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

