// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct TumVehicleId {
 *     OCTET_STRING_t *vehicleIdentity;
 *     IA5String_t *licPlateState;
 *     IA5String_t *licPlateNumVeh;
 *     IA5String_t *licPlateNumTrailer;
 *     struct UserId *userId;
 *     asn_struct_ctx_t _asn_ctx;
 * } TumVehicleId_t
 * }
 */
public class TumVehicleId_t extends TumVehicleId {

    TumVehicleId_t() {
        // Should not be called directly
    }
}

