// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct UserData {
 *     DDateTime_t timeStamp;
 *     OBJECT_IDENTIFIER_t svcProvID;
 *     TumVehicleId_t vehicleID;
 *     VehicleTypes_t vehicleType;
 *     struct VehicleDescription *vehicleDescription;
 *     asn_struct_ctx_t _asn_ctx;
 * } UserData_t
 * }
 */
public class UserData_t extends UserData {

    UserData_t() {
        // Should not be called directly
    }
}

