// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VehicleAxles {
 *     Int1Unsigned_t vehicleFirstAxleHeight;
 *     VehicleAxlesNumber_t vehicleAxlesNumber;
 *     asn_struct_ctx_t _asn_ctx;
 * }
 * }
 */
public class VehicleAxles {

    VehicleAxles() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MessageFrame_h.C_LONG.withName("vehicleFirstAxleHeight"),
        VehicleAxlesNumber.layout().withName("vehicleAxlesNumber"),
        asn_struct_ctx_s.layout().withName("_asn_ctx")
    ).withName("VehicleAxles");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong vehicleFirstAxleHeight$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vehicleFirstAxleHeight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * Int1Unsigned_t vehicleFirstAxleHeight
     * }
     */
    public static final OfLong vehicleFirstAxleHeight$layout() {
        return vehicleFirstAxleHeight$LAYOUT;
    }

    private static final long vehicleFirstAxleHeight$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * Int1Unsigned_t vehicleFirstAxleHeight
     * }
     */
    public static final long vehicleFirstAxleHeight$offset() {
        return vehicleFirstAxleHeight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * Int1Unsigned_t vehicleFirstAxleHeight
     * }
     */
    public static long vehicleFirstAxleHeight(MemorySegment struct) {
        return struct.get(vehicleFirstAxleHeight$LAYOUT, vehicleFirstAxleHeight$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * Int1Unsigned_t vehicleFirstAxleHeight
     * }
     */
    public static void vehicleFirstAxleHeight(MemorySegment struct, long fieldValue) {
        struct.set(vehicleFirstAxleHeight$LAYOUT, vehicleFirstAxleHeight$OFFSET, fieldValue);
    }

    private static final GroupLayout vehicleAxlesNumber$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("vehicleAxlesNumber"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VehicleAxlesNumber_t vehicleAxlesNumber
     * }
     */
    public static final GroupLayout vehicleAxlesNumber$layout() {
        return vehicleAxlesNumber$LAYOUT;
    }

    private static final long vehicleAxlesNumber$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VehicleAxlesNumber_t vehicleAxlesNumber
     * }
     */
    public static final long vehicleAxlesNumber$offset() {
        return vehicleAxlesNumber$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VehicleAxlesNumber_t vehicleAxlesNumber
     * }
     */
    public static MemorySegment vehicleAxlesNumber(MemorySegment struct) {
        return struct.asSlice(vehicleAxlesNumber$OFFSET, vehicleAxlesNumber$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VehicleAxlesNumber_t vehicleAxlesNumber
     * }
     */
    public static void vehicleAxlesNumber(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, vehicleAxlesNumber$OFFSET, vehicleAxlesNumber$LAYOUT.byteSize());
    }

    private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final GroupLayout _asn_ctx$layout() {
        return _asn_ctx$LAYOUT;
    }

    private static final long _asn_ctx$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final long _asn_ctx$offset() {
        return _asn_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static MemorySegment _asn_ctx(MemorySegment struct) {
        return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

