// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct VehicleAxlesNumber {
 *     TyreConfiguration_t tyreConfiguration;
 *     NumberOfAxles_t numberOfAxles;
 *     asn_struct_ctx_t _asn_ctx;
 * } VehicleAxlesNumber_t
 * }
 */
public class VehicleAxlesNumber_t extends VehicleAxlesNumber {

    VehicleAxlesNumber_t() {
        // Should not be called directly
    }
}

