// Generated by jextract

package j2735_2024_MessageFrame;

import java.lang.foreign.*;
import java.util.function.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct VehTypeCharges {
 *     VehicleTypes_t vehType;
 *     PaymentFee_t charges;
 *     struct SpecialCharges *specialCharges;
 *     asn_struct_ctx_t _asn_ctx;
 * }
 * }
 */
public class VehTypeCharges {

    VehTypeCharges() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MessageFrame_h.C_LONG.withName("vehType"),
        PaymentFee.layout().withName("charges"),
        MessageFrame_h.C_POINTER.withName("specialCharges"),
        asn_struct_ctx_s.layout().withName("_asn_ctx")
    ).withName("VehTypeCharges");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong vehType$LAYOUT = (OfLong)$LAYOUT.select(groupElement("vehType"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * VehicleTypes_t vehType
     * }
     */
    public static final OfLong vehType$layout() {
        return vehType$LAYOUT;
    }

    private static final long vehType$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * VehicleTypes_t vehType
     * }
     */
    public static final long vehType$offset() {
        return vehType$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * VehicleTypes_t vehType
     * }
     */
    public static long vehType(MemorySegment struct) {
        return struct.get(vehType$LAYOUT, vehType$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * VehicleTypes_t vehType
     * }
     */
    public static void vehType(MemorySegment struct, long fieldValue) {
        struct.set(vehType$LAYOUT, vehType$OFFSET, fieldValue);
    }

    private static final GroupLayout charges$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("charges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PaymentFee_t charges
     * }
     */
    public static final GroupLayout charges$layout() {
        return charges$LAYOUT;
    }

    private static final long charges$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PaymentFee_t charges
     * }
     */
    public static final long charges$offset() {
        return charges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PaymentFee_t charges
     * }
     */
    public static MemorySegment charges(MemorySegment struct) {
        return struct.asSlice(charges$OFFSET, charges$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PaymentFee_t charges
     * }
     */
    public static void charges(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, charges$OFFSET, charges$LAYOUT.byteSize());
    }

    private static final AddressLayout specialCharges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("specialCharges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct SpecialCharges *specialCharges
     * }
     */
    public static final AddressLayout specialCharges$layout() {
        return specialCharges$LAYOUT;
    }

    private static final long specialCharges$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct SpecialCharges *specialCharges
     * }
     */
    public static final long specialCharges$offset() {
        return specialCharges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct SpecialCharges *specialCharges
     * }
     */
    public static MemorySegment specialCharges(MemorySegment struct) {
        return struct.get(specialCharges$LAYOUT, specialCharges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct SpecialCharges *specialCharges
     * }
     */
    public static void specialCharges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(specialCharges$LAYOUT, specialCharges$OFFSET, fieldValue);
    }

    private static final GroupLayout _asn_ctx$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("_asn_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final GroupLayout _asn_ctx$layout() {
        return _asn_ctx$LAYOUT;
    }

    private static final long _asn_ctx$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static final long _asn_ctx$offset() {
        return _asn_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static MemorySegment _asn_ctx(MemorySegment struct) {
        return struct.asSlice(_asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * asn_struct_ctx_t _asn_ctx
     * }
     */
    public static void _asn_ctx(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, _asn_ctx$OFFSET, _asn_ctx$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

