// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct WDMSFleetData {
 *     struct NtcipPavementTreatment *pavementTreat;
 *     ITIS_ITIStext_t *routingAdvice;
 *     asn_struct_ctx_t _asn_ctx;
 * } WDMSFleetData_t
 * }
 */
public class WDMSFleetData_t extends WDMSFleetData {

    WDMSFleetData_t() {
        // Should not be called directly
    }
}

