// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct WeatherProbe {
 *     AmbientAirTemperature_t *airTemp;
 *     AmbientAirPressure_t *airPressure;
 *     struct WiperSet *rainRates;
 *     asn_struct_ctx_t _asn_ctx;
 * } WeatherProbe_t
 * }
 */
public class WeatherProbe_t extends WeatherProbe {

    WeatherProbe_t() {
        // Should not be called directly
    }
}

