// Generated by jextract

package j2735_2024_MessageFrame;

/**
 * {@snippet lang=c :
 * typedef struct WeightCharges {
 *     WeightCharges_PR present;
 *     union WeightCharges_u {
 *         TotalWeightCharges_t totalWeightCharges;
 *         PerAxleWeightCharges_t perAxleWeightCharges;
 *     } choice;
 *     asn_struct_ctx_t _asn_ctx;
 * } WeightCharges_t
 * }
 */
public class WeightCharges_t extends WeightCharges {

    WeightCharges_t() {
        // Should not be called directly
    }
}

