spring.application.name: j2735-2024-api
server.port: 4000
spring.main.web-application-type: servlet

springdoc.swagger-ui.path: /swagger-ui.html
springdoc.api-docs.path: /api-docs

j2735.api:
  # Use a large default value for text encoding, because the XML encodings for some messages,
  # such as MAPs and TIMs, can be quite large
  text-buffer-size: 262144
  # UPER binary is a more compact encoding, so we can use a smaller buffer size.
  uper-buffer-size: 8192
  error-buffer-size: 256
  library-path: /home/libasnapplication.so
  windows-library-path: C:/temp/asnapplication.dll
