/*
   Copyright 2025-2026 Neaera Consulting LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package j2735ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.nio.charset.StandardCharsets;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentLinkedDeque;
import java.util.concurrent.atomic.AtomicInteger;
import lombok.extern.slf4j.Slf4j;

import static j2735ffm.AsnEncoding.JER;
import static j2735ffm.AsnEncoding.XER;
import static j2735ffm.AsnEncoding.UPER;
import static j2735ffm.AsnEncoding.OER;

/**
 * Functions for interconverting J2735 (2024) MessageFrames between XER, JER, UPER, and OER
 * encodings by calling native functions generated by asn1c.
 *
 * @author Ivan Yourshaw
 */
@Slf4j
public class GeneralCodec {

    /**
     * Output buffer size for XER and JSON.  Messages larger than this can't be produced.
     */
    public final long textBufferSize;

    /**
     * Buffer size for UPER binary messages.  Messages larger than this can't be produced.
     */
    public final long binaryBufferSize;

    /**
     * Buffer size for error messages returned from the native library.
     */
    public final long errorBufferSize;

    /**
     * Native buffers that no conversion is using.  Allocating and zeroing the buffers for
     * each message costs more than converting a small message, so they are kept and handed
     * out again.  There are as many as there were conversions running at the same time, up
     * to {@link #MAX_KEPT_BUFFERS}.
     */
    private final ConcurrentLinkedDeque<Buffers> idleBuffers = new ConcurrentLinkedDeque<>();

    /**
     * The most sets of buffers a codec keeps.  A conversion that finds them all in use
     * allocates buffers of its own and frees them when it is done.
     */
    private static final int MAX_KEPT_BUFFERS = Runtime.getRuntime().availableProcessors();

    // The number of kept sets made so far, idle or in use
    private final AtomicInteger keptBuffers = new AtomicInteger();

    // The buffers of one conversion at a time, allocated when first asked for.  The memory of
    // a kept set is released once the codec is no longer reachable.
    private final class Buffers {
        private final boolean kept;
        private final Arena arena;
        private final MemorySegment error;
        private MemorySegment textInput;
        private MemorySegment binaryInput;
        private MemorySegment textOutput;
        private MemorySegment binaryOutput;

        Buffers(boolean kept) {
            this.kept = kept;
            this.arena = kept ? Arena.ofAuto() : Arena.ofConfined();
            this.error = arena.allocate(errorBufferSize);
        }

        // size is textBufferSize or binaryBufferSize
        MemorySegment input(long size) {
            if (size == textBufferSize) {
                if (textInput == null) {
                    textInput = arena.allocate(size);
                }
                return textInput;
            }
            if (binaryInput == null) {
                binaryInput = arena.allocate(size);
            }
            return binaryInput;
        }

        MemorySegment output(long size) {
            if (size == textBufferSize) {
                if (textOutput == null) {
                    textOutput = arena.allocate(size);
                }
                return textOutput;
            }
            if (binaryOutput == null) {
                binaryOutput = arena.allocate(size);
            }
            return binaryOutput;
        }

    }

    private Buffers borrowBuffers() {
        final Buffers buffers = idleBuffers.pollFirst();
        if (buffers != null) {
            return buffers;
        }
        if (keptBuffers.incrementAndGet() <= MAX_KEPT_BUFFERS) {
            return new Buffers(true);
        }
        keptBuffers.decrementAndGet();
        return new Buffers(false);
    }

    // To be called by the thread that borrowed them
    private void returnBuffers(Buffers buffers) {
        if (buffers.kept) {
            idleBuffers.offerFirst(buffers);
        } else {
            buffers.arena.close();
        }
    }

    private static final Platform PLATFORM = detectPlatform();

    /**
     * Detect the platform of the running OS.
     * @return The detected platform
     */
    protected static Platform detectPlatform() {
        String os = LibraryDetector.detectOS();
        return switch (os) {
            case "linux" -> Platform.LINUX;
            case "windows" -> Platform.WINDOWS;
            default -> throw new UnsupportedOperationException(
                "Unsupported operating system: " + os);
        };
    }

    /**
     * Constructor.  Configures the library and loads the underlying native library.
     * Looks for the library appropriate for the current platform and architecture,
     * with in the default location at the same relative path where this jar is running.
     * @param textBufferSize - Size of the input or output buffer for text encodings (XER)
     * @param binaryBufferSize - Size of the input or output buffer for UPER or OER binary encoding.
     * @param errorBufferSize - Size of the buffer for error messages from the native library.
     */
    public GeneralCodec(long textBufferSize, long binaryBufferSize, long errorBufferSize) {
        this.textBufferSize = textBufferSize;
        this.binaryBufferSize = binaryBufferSize;
        this.errorBufferSize = errorBufferSize;
        Path libraryPath = LibraryDetector.findLibrary(Path.of("."), "asnapplication");
        loadLibrary(libraryPath);
        log.info("GeneralCodec initialized with textBufferSize: {}, uperBufferSize: {}, libraryPath: {}",
            textBufferSize, binaryBufferSize, libraryPath);
    }

    /**
     * Constructor.  Configures the library and loads the underlying native library
     * @param textBufferSize - Size of the input or output buffer for text encodings (XER)
     * @param binaryBufferSize - Size of the input or output buffer for UPER or OER binary encoding.
     * @param errorBufferSize - Size of the buffer for error messages from the native library.
     * @param libraryPath - Absolute or relative path to the native library, e.g. "/usr/lib/libasnapplication.so"
     */
    public GeneralCodec(long textBufferSize, long binaryBufferSize, long errorBufferSize,
            Path libraryPath) {
        this.textBufferSize = textBufferSize;
        this.binaryBufferSize = binaryBufferSize;
        this.errorBufferSize = errorBufferSize;
        loadLibrary(libraryPath);
        log.info("GeneralCodec initialized with textBufferSize: {}, uperBufferSize: {}, libraryPath: {}",
            textBufferSize, binaryBufferSize, libraryPath);
    }



    /**
     * load library with given class loader.
     * @param libraryPath The URI of the library resource
     */
    private void loadLibrary(Path libraryPath) {
        // Load the library into a garbage-collected arena
        if (libraryPath == null) {
            // LibraryDetector.findLibrary returns null when auto-detection finds nothing
            String errMsg = "Library not found: no native library for this platform in the working directory";
            log.error(errMsg);
            throw new RuntimeException(errMsg);
        }
        if (!Files.exists(libraryPath)) {
            String errMsg = String.format("Library not found at path: %s", libraryPath);
            log.error(errMsg);
            throw new RuntimeException(errMsg);
        }
        try {
            Arena arena = Arena.ofAuto();
            SymbolLookup lookup = SymbolLookup.libraryLookup(libraryPath, arena);
            log.info("Loaded library: {}", libraryPath);
            var symbol = lookup.find("convert_bytes");
            if (symbol.isPresent()) {
                log.info("found symbol convert_bytes: {}", symbol);
            } else {
                throw new RuntimeException("symbol 'convert_bytes' not found in the library");
            }
            // Note: Assign the lookup to a static field in the generated code.
            // This will prevent the library from being garbage collected until
            // the class loader that loaded the "convert_h" class is itself garbage collected.
            // Normally that would happen when the JVM exits, but could happen sooner if this library is
            // loaded dynamically by a custom class loader or is used in the context of OSGI or
            // something. We do this instead of using the global arena to prevent memory leaks
            // in case of that unlikely, but possible, scenario.
            if (PLATFORM == Platform.WINDOWS) {
                generated.windows.convert_h.SYMBOL_LOOKUP = lookup;
            } else {
                generated.linux.convert_h.SYMBOL_LOOKUP = lookup;
            }
        } catch (Throwable e) {
            String errMsg = String.format("Error loading library: %s: %s", libraryPath, e);
            log.error(errMsg);
            throw new RuntimeException(errMsg, e);
        }
    }


    /**
     * General purpose conversion function that can convert any PDU to or from
     * any encoding.  Includes constraint check.
     * @param inputBytes Input byte array: XER, or UPER or OER binary
     * @param pdu The name of the PDU, e.g., "MessageFrame", "MessageFrame", "VehicleEventFlags", etc.
     * @param fromEncoding Input encoding, may be "xer", "uper", or "oer"
     * @param toEncoding Output encoding, may be "xer", "uper", or "oer"
     * @return The encoded message as bytes or UTF-8 string
     */
    public byte[] convertGeneral(byte[] inputBytes, String pdu, AsnEncoding fromEncoding, AsnEncoding toEncoding) {
        return convertGeneral(inputBytes, pdu, fromEncoding, toEncoding, true);
    }

    /**
     * General purpose conversion function that can convert any PDU to or from
     * any encoding.
     * @param inputBytes Input byte array: XER, or UPER or OER binary
     * @param pdu The name of the PDU, e.g., "MessageFrame", "MessageFrame", "VehicleEventFlags", etc.
     * @param fromEncoding Input encoding, may be "xer", "uper", or "oer"
     * @param toEncoding Output encoding, may be "xer", "uper", or "oer"
     * @param checkConstraints whether to check constraints
     * @return The encoded message as bytes or UTF-8 string
     */
    public byte[] convertGeneral(byte[] inputBytes, String pdu, AsnEncoding fromEncoding,
            AsnEncoding toEncoding, boolean checkConstraints) {
        log.debug("convertGeneral PDU: {}, {} -> {}", pdu, fromEncoding, toEncoding);
        validateSupportedEncoding(fromEncoding, toEncoding);
        final long inputBufferSize = fromEncoding.isBinary() ? binaryBufferSize : textBufferSize;
        validateInputSize(inputBytes, inputBufferSize);
        final long outputBufferSize = toEncoding.isBinary() ? binaryBufferSize : textBufferSize;
        return convertSingleMessage(inputBufferSize, outputBufferSize, inputBytes, pdu,
            fromEncoding.getName(), toEncoding.getName(), checkConstraints);
    }

    /**
     * Batch conversion reusing the input and output buffers.  Includes constraint check.
     * @param inputBytesList List of encoded messages
     * @param pdu The PDU to convert
     * @param fromEncoding The input encoding: xer, oer, or uper
     * @param toEncoding The output encoding: xer, oer, or uper
     * @return List of decoded messages
     */
    public List<byte[]> convertBatch(List<byte[]> inputBytesList, String pdu,
        AsnEncoding fromEncoding, AsnEncoding toEncoding) {
        return convertBatch(inputBytesList, pdu, fromEncoding, toEncoding, true);
    }

    /**
     * Batch conversion reusing the input and output buffers
     * @param inputBytesList List of encoded messages
     * @param pdu The PDU to convert
     * @param fromEncoding The input encoding: xer, oer, or uper
     * @param toEncoding The output encoding: xer, oer, or uper
     * @param checkConstraints Whether to check constraints
     * @return List of decoded messages
     */
    public List<byte[]> convertBatch(List<byte[]> inputBytesList, String pdu,
        AsnEncoding fromEncoding, AsnEncoding toEncoding, boolean checkConstraints) {
        log.debug("convertBatch PDU: {}, {} -> {}", pdu, fromEncoding, toEncoding);
        validateSupportedEncoding(fromEncoding, toEncoding);
        final long inputBufferSize = fromEncoding.isBinary() ? binaryBufferSize : textBufferSize;
        final long outputBufferSize = toEncoding.isBinary() ? binaryBufferSize : textBufferSize;
        List<byte[]> outputBytesList = new ArrayList<>();
        final Buffers buffers = borrowBuffers();
        try (var arena = Arena.ofConfined()) {
            MemorySegment inputBuffer = buffers.input(inputBufferSize);
            MemorySegment outputBuffer = buffers.output(outputBufferSize);
            MemorySegment errorBuffer = buffers.error;
            MemorySegment pduName = arena.allocateFrom(pdu, StandardCharsets.UTF_8);
            MemorySegment fromEncodingSeg = arena.allocateFrom(fromEncoding.getName(),
                StandardCharsets.UTF_8);
            MemorySegment toEncodingSeg = arena.allocateFrom(toEncoding.getName(),
                StandardCharsets.UTF_8);
            for (byte[] inputBytes : inputBytesList) {
                if (inputBytes.length > inputBufferSize) {
                    String errMsg = String.format("One batched input message is too large: %d > %d",
                        inputBytes.length, inputBufferSize);
                    log.error(errMsg);
                    continue;
                }
                try {
                    byte[] outputBytes = convert(inputBytes, inputBuffer, pduName,
                        fromEncodingSeg, toEncodingSeg, outputBuffer, outputBufferSize, errorBuffer,
                        errorBufferSize, checkConstraints);
                    outputBytesList.add(outputBytes);
                } catch (ConvertException ce) {
                    log.error("error converting one batched item", ce);
                }
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        } finally {
            returnBuffers(buffers);
        }
        return outputBytesList;
    }

    /**
     * Convert an XER encoded MessageFrame to UPER.
     * Always check constraints going to UPER.
     * @param pdu The name of the PDU, e.g., "MessageFrame"
     * @param xer The XER encoded MessageFrame
     * @return Byte array with the UPER encoding
     */
    public byte[] xerToUper(String pdu, String xer) {
        return textToBinaryEncoding(XER.getName(), UPER.getName(), pdu, xer);
    }

    /**
     * Convert a JER encoded MessageFrame to UPER.
     * Always check constraints going to UPER.
     * @param pdu The PDU to encode
     * @param jer The JER encoded MessageFrame
     * @return Byte array with the UPER encoding
     */
    public byte[] jerToUper(String pdu, String jer) {
        return textToBinaryEncoding(JER.getName(), UPER.getName(), pdu, jer);
    }

    /**
     * Convert an UPER encoded MessageFrame to XER.  Includes constraint check.
     * @param pdu The PDU to encode
     * @param uper The UPER encoded MessageFrame
     * @return XER encoded result
     */
    public String uperToXer(String pdu, byte[] uper) {
        return uperToXer(pdu, uper, true);
    }

    /**
     * Convert an UPER encoded MessageFrame to JER.  Includes constraint check.
     * @param pdu The PDU to encode
     * @param uper The UPER encoded MessageFrame
     * @return JER encoded result
     */
    public String uperToJer(String pdu, byte[] uper) {
        return uperToJer(pdu, uper, true);
    }

    /**
     * Convert an UPER encoded MessageFrame to XER
     * @param pdu The PDU to encode
     * @param uper The UPER encoded MessageFrame
     * @param checkConstraints Whether to check constraints.
     * @return XER encoded result
     */
    public String uperToXer(String pdu, byte[] uper, boolean checkConstraints) {
        return binaryToTextEncoding(UPER.getName(), XER.getName(), pdu, uper, checkConstraints);
    }

    /**
     * Convert an UPER encoded MessageFrame to JER
     * @param pdu The PDU to encode
     * @param uper The UPER encoded MessageFrame
     * @param checkConstraints Whether to check constraints.
     * @return JER encoded result
     */
    public String uperToJer(String pdu, byte[] uper, boolean checkConstraints) {
        return binaryToTextEncoding(UPER.getName(), JER.getName(), pdu, uper, checkConstraints);
    }



    /**
     * Convert an XER encoded PDU to OER.
     * Always check constraints going to OER.
     * @param xer The XER encoded PDU
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @return Byte array with the OER encoding
     */
    public byte[] xerToOer(String pdu, String xer) {
        return textToBinaryEncoding(XER.getName(), OER.getName(), pdu, xer);
    }

    /**
     * Convert a JER encoded PDU to OER.
     * Always check constraints going to OER.
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @param jer The JER encoded PDU
     * @return Byte array with the OER encoding
     */
    public byte[] jerToOer(String pdu, String jer) {
        return textToBinaryEncoding(JER.getName(), OER.getName(), pdu, jer);
    }

    /**
     * Convert an OER encoded PDU to XER. Includes constraint check.
     * @param oer The OER encoded PDU
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @return XER encoded result
     */
    public String oerToXer(String pdu, byte[] oer) {
        return oerToXer(pdu, oer, true);
    }

    /**
     * Convert an OER encoded PDU to JER. Includes constraint check.
     * @param oer The OER encoded PDU
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @return JER encoded result
     */
    public String oerToJer(String pdu, byte[] oer) {
        return oerToJer(pdu, oer, true);
    }

    /**
     * Convert an OER encoded PDU to XER
     * @param oer The OER encoded PDU
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @param checkConstraints Whether to check constraints
     * @return XER encoded result
     */
    public String oerToXer(String pdu, byte[] oer, boolean checkConstraints) {
        return binaryToTextEncoding(OER.getName(), XER.getName(), pdu, oer, checkConstraints);
    }

    /**
     * Convert an OER encoded PDU to JER
     * @param oer The OER encoded PDU
     * @param pdu The Protocol Data Unit, e.g. "Ieee1609Dot2Data"
     * @param checkConstraints Whether to check constraints
     * @return JER encoded result
     */
    public String oerToJer(String pdu, byte[] oer, boolean checkConstraints) {
        return binaryToTextEncoding(OER.getName(), JER.getName(), pdu, oer, checkConstraints);
    }

    private String binaryToTextEncoding(String fromEncoding, String toEncoding,
            String pdu, byte[] bytes, boolean checkConstraints) {
        log.trace("Received {} bytes", bytes.length);
        validateInputSize(bytes, binaryBufferSize);
        byte[] encodedBytes = convertSingleMessage(binaryBufferSize, textBufferSize, bytes, pdu,
            fromEncoding, toEncoding, checkConstraints);
        return new String(encodedBytes, StandardCharsets.UTF_8);
    }

    private byte[] textToBinaryEncoding(String fromEncoding, String toEncoding,
            String pdu, String text) {
        log.trace("text: {}", text);
        final byte[] textBytes = text.getBytes(StandardCharsets.UTF_8);
        validateTextSize(textBytes);
        return convertSingleMessage(textBufferSize, binaryBufferSize, textBytes,
            pdu, fromEncoding, toEncoding, true);
    }

    // Converts a single message in buffers that are kept for the next one
    private byte[] convertSingleMessage(long inputBufferSize, long outputBufferSize,
            byte[] inputBytes, String pdu, String fromEncoding, String toEncoding,
            boolean checkConstraints) {
        final Buffers buffers = borrowBuffers();
        // The arena is for the names of the PDU and the encodings
        try (var arena = Arena.ofConfined()) {
            return convert(arena, inputBytes, fromEncoding,
                toEncoding, buffers.input(inputBufferSize), buffers.output(outputBufferSize),
                outputBufferSize, buffers.error, errorBufferSize, pdu, checkConstraints);
        } catch (Exception e) {
            log.error("GeneralCodec: Exception converting message", e);
            throw new RuntimeException(e);
        } finally {
            returnBuffers(buffers);
        }
    }

    // Converts a single message with the given pre-allocated input/output buffers
    // Does not dispose of the buffers.
    private byte[] convert(Arena arena, final byte[] bytes,
            final String fromEncoding, final String toEncoding, MemorySegment inputBuffer,
            MemorySegment outputBuffer, long outputBufferSize, MemorySegment errorBuffer,
            long errorBufferSize, final String pdu, boolean checkConstraints)
            throws ConvertException {
        log.debug("convert: {} {}, check constraints: {}", fromEncoding, toEncoding, checkConstraints);
        MemorySegment pduName = arena.allocateFrom(pdu, StandardCharsets.UTF_8);
        MemorySegment fromEncodingSeg = arena.allocateFrom(fromEncoding,
            StandardCharsets.UTF_8);
        MemorySegment toEncodingSeg = arena.allocateFrom(toEncoding, StandardCharsets.UTF_8);
        return convert(bytes, inputBuffer, pduName, fromEncodingSeg, toEncodingSeg,
            outputBuffer, outputBufferSize, errorBuffer, errorBufferSize, checkConstraints);
    }

    // Converts a single message with the given pre-allocated input/output buffers
    // Does not dispose of the buffers.  Does not allocate any buffers including pdu
    // and encoding string buffers.
    private byte[] convert(final byte[] bytes,
        MemorySegment inputBuffer, MemorySegment pduName,
        MemorySegment fromEncodingSeg, MemorySegment toEncodingSeg,
        MemorySegment outputBuffer, long outputBufferSize, MemorySegment errorBuffer,
        long errorBufferSize, boolean checkConstraints)
        throws ConvertException {

        byte[] outputArray = null;

        MemorySegment heapBytes = MemorySegment.ofArray(bytes);
        inputBuffer.copyFrom(heapBytes);

        long numOut = 0;
        int iCheckConstraints = checkConstraints ? 1 : 0;
        try {
            if (PLATFORM == Platform.WINDOWS) {
                numOut = generated.windows.convert_h.convert_bytes(pduName, fromEncodingSeg,
                    toEncodingSeg, inputBuffer,
                    bytes.length, outputBuffer, outputBufferSize, errorBuffer, errorBufferSize,
                    iCheckConstraints);
            } else {
                numOut = generated.linux.convert_h.convert_bytes(pduName, fromEncodingSeg,
                    toEncodingSeg, inputBuffer,
                    bytes.length, outputBuffer, outputBufferSize, errorBuffer, errorBufferSize,
                    iCheckConstraints);
            }
        } catch (Throwable ex) {
            log.error("error converting",ex);
            throw ex;
        }
        log.debug("numOut: {}", numOut);
        if (numOut < 0) {
            // Error was returned
            String error = errorBuffer.getString(0);
            log.error(error);
            throw new ConvertException(error);
        }
        outputArray = new byte[(int) numOut];
        MemorySegment heapOutput = MemorySegment.ofArray(outputArray);
        MemorySegment.copy(outputBuffer, 0, heapOutput, 0, numOut);

        return outputArray;
    }

    // Validate if the input and output encodings are supported
    private void validateSupportedEncoding(AsnEncoding fromEncoding, AsnEncoding toEncoding) {
        if (!fromEncoding.isSupported()) {
            String errMsg = String.format("Unsupported fromEncoding: %s", fromEncoding);
            log.error(errMsg);
            throw new IllegalArgumentException(errMsg);
        }
        if (!toEncoding.isSupported()) {
            String errMsg = String.format("Unsupported toEncoding: %s", toEncoding);
            log.error(errMsg);
            throw new IllegalArgumentException(errMsg);
        }
    }

    // Validate text input, as UTF-8, fits in text buffer
    private void validateTextSize(byte[] xer) {
        final int xerByteLength = xer.length;
        if (xerByteLength > textBufferSize) {
            String errMsg = String.format("Input XER message too large: %d > %d", xerByteLength,
                textBufferSize);
            log.error(errMsg);
            throw new IllegalArgumentException(errMsg);
        }
    }

    // Validate byte input size (binary encoding or text encoded as bytes)
    private void validateInputSize(byte[] inputBytes, long inputBufferSize) {
        if (inputBytes.length > inputBufferSize) {
            String errMsg = String.format("Input message too large: %d > %d",
                inputBytes.length, inputBufferSize);
            log.error(errMsg);
            throw new IllegalArgumentException(errMsg);
        }
    }

}
