package j2735ffm;

import java.nio.file.Path;

/**
 * Functions for interconverting Ieee1609Dot2Data between XER, JER, and OER encodings
 * by calling native functions generated by asn1c.
 *
 * @author Ivan Yourshaw
 */
public class Ieee1609Dot2DataCodec extends GeneralCodec {

  /** PDU name for Ieee1609Dot2Data. */
  public final static String IEEE1609_DOT2_DATA_PDU = "Ieee1609Dot2Data";

  /**
   * Constructor.  Configures the library and loads the underlying native library
   * @param textBufferSize - Size of the input or output buffer for text encodings (XER)
   * @param oerBufferSize - Size of the input or output buffer for OER binary encoding.
   * @param errorBufferSize - Size of the buffer for error messages from the native library.
   * @param libraryPath - Absolute or relative path to the native library, e.g. "/usr/lib/libasnapplication.so"
   */
  public Ieee1609Dot2DataCodec(long textBufferSize, long oerBufferSize, long errorBufferSize,
      Path libraryPath) {
    super(textBufferSize, oerBufferSize, errorBufferSize, libraryPath);
  }

  /**
   * Constructor.  Configures the library and loads the underlying native library, tries to
   * find library at default location next to this JAR.
   * @param textBufferSize - Size of the input or output buffer for text encodings (XER)
   * @param oerBufferSize - Size of the input or output buffer for OER binary encoding.
   * @param errorBufferSize - Size of the buffer for error messages from the native library.
   */
  public Ieee1609Dot2DataCodec(long textBufferSize, long oerBufferSize, long errorBufferSize) {
    super(textBufferSize, oerBufferSize, errorBufferSize);
  }

  /**
   * Convert an XER encoded Ieee1609Dot2Data to OER
   * @param xer The XER encoded Ieee1609Dot2Data
   * @return Byte array with the OER encoding
   */
  public byte[] xerToOer(String xer) {
    return super.xerToOer(IEEE1609_DOT2_DATA_PDU, xer);
  }

  /**
   * Convert a JER encoded Ieee1609Dot2Data to OER
   * @param jer The JER encoded Ieee1609Dot2Data
   * @return Byte array with the OER encoding
   */
  public byte[] jerToOer(String jer) {
    return super.jerToOer(IEEE1609_DOT2_DATA_PDU, jer);
  }
  /**
   * Convert an OER encoded Ieee1609Dot2Data to XER
   * @param oer The OER encoded Ieee1609Dot2Data
   * @return XER encoded result
   */
  public String oerToXer(byte[] oer) {
    return super.oerToXer(IEEE1609_DOT2_DATA_PDU, oer);
  }

  /**
   * Convert an OER encoded Ieee1609Dot2Data to JER
   * @param oer The OER encoded Ieee1609Dot2Data
   * @return JER encoded result
   */
  public String oerToJer(byte[] oer) {
    return super.oerToJer(IEEE1609_DOT2_DATA_PDU, oer);
  }

  /**
   * Convert an OER encoded Ieee1609Dot2Data to XER. Allows producing
   * XER with constraint violations.  This is usually not recommended but can be useful for
   * diagnostic purposes.
   * @param oer The OER encoded Ieee1609Dot2Data
   * @return XER encoded result
   */
  public String oerToXerNoConstraintCheck(byte[] oer) {
    return super.oerToXer(IEEE1609_DOT2_DATA_PDU, oer, false);
  }

  /**
   * Convert an OER encoded Ieee1609Dot2Data to JER. Allows producing
   * JER with constraint violations.  This is usually not recommended but can be useful for
   * diagnostic purposes.
   * @param oer The OER encoded Ieee1609Dot2Data
   * @return JER encoded result
   */
  public String oerToJerNoConstraintCheck(byte[] oer) {
    return super.oerToJer(IEEE1609_DOT2_DATA_PDU, oer, false);
  }

}
