/*
   Copyright 2025 Neaera Consulting LLC

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package j2735ffm;

import java.nio.file.Path;
import lombok.extern.slf4j.Slf4j;

/**
 * Functions for interconverting J2735 (2024) MessageFrames between XER, and UPER encodings
 * by calling native functions generated by asn1c.
 *
 * @author Ivan Yourshaw
 */
@Slf4j
public class MessageFrameCodec extends GeneralCodec {

    public final static String MESSAGE_FRAME_PDU = "MessageFrame";

    /**
     * Constructor.  Configures the library and loads the underlying native library
     * @param textBufferSize - Size of the input or output buffer for text encodings (XER)
     * @param uperBufferSize - Size of the input or output buffer for UPER binary encoding.
     * @param libraryPath - Absolute or relative path to the native library, e.g. "/usr/lib/libasnapplication.so"
     */
    public MessageFrameCodec(long textBufferSize, long uperBufferSize, long errorBufferSize,
            Path libraryPath) {
        super(textBufferSize, uperBufferSize, errorBufferSize, libraryPath);
    }

    /**
     * Convert an XER encoded MessageFrame to UPER
     * @param xer The XER encoded MessageFrame
     * @return Byte array with the UPER encoding
     */
    public byte[] xerToUper(String xer) {
        return super.xerToUper(MESSAGE_FRAME_PDU, xer);
    }

    /**
     * Convert an UPER encoded MessageFrame to XER
     * @param uper The UPER encoded MessageFrame
     * @return XER encoded result
     */
    public String uperToXer(byte[] uper) {
        return super.uperToXer(MESSAGE_FRAME_PDU, uper);
    }

}
