package j2735ffm;

import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.ValueLayout;
import java.nio.charset.StandardCharsets;

import static j2735_2024_MessageFrame.TumData_h.*;
import j2735_2024_MessageFrame.*;
import lombok.extern.slf4j.Slf4j;


/**
 * Functions for interconverting J2735 (2024) TumData between XER, JER, and UPER encodings
 * by calling native functions generated by asn1c.
 *
 * @author John Wiens
 */
@Slf4j
public class TumDataCodec {

    /**
     * Output buffer size for XER and JSON.  Messages larger than this can't be produced.
     */
    public final long textBufferSize;

    /**
     * Buffer size for UPER binary messages.  Messages larger than this can't be produced.
     */
    public final long uperBufferSize;

    /**
     * Buffer size for internal representation of a TumData_t struct
     */
    public final long tumDataAllocateSize;

    public final long asnCodecCtxMaxStackSize;

    public TumDataCodec() {
        this.textBufferSize = 262144L;
        this.uperBufferSize = 8192L;
        this.tumDataAllocateSize = 16384L;
        this.asnCodecCtxMaxStackSize = 30000L;
        log.info("TumDataCodec initialized with defaults: textBufferSize: {}, uperBufferSize: {}, tumDataAllocateSize: {}, asnCodecCtxMaxStackSize: {}",
                textBufferSize, uperBufferSize, tumDataAllocateSize, asnCodecCtxMaxStackSize);
    }

    public TumDataCodec(
            long textBufferSize,
            long uperBufferSize,
            long tumDataAllocateSize,
            long asnCodecCtxMaxStackSize) {
        this.textBufferSize = textBufferSize;
        this.uperBufferSize = uperBufferSize;
        this.tumDataAllocateSize = tumDataAllocateSize;
        this.asnCodecCtxMaxStackSize = asnCodecCtxMaxStackSize;
        log.info("TumDataCodec initialized with textBufferSize: {}, uperBufferSize: {}, tumDataAllocateSize: {}, asnCodecCtxMaxStackSize: {}",
                textBufferSize, uperBufferSize, tumDataAllocateSize, asnCodecCtxMaxStackSize);
    }


    public byte[] xerToUper(String xer) {
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment inputBuffer = arena.allocate(textBufferSize);
            xerToTumData(arena, xer, tumData, inputBuffer);
            MemorySegment outputBuffer = arena.allocate(uperBufferSize);
            return tumDataToUper(arena, tumData, uperBufferSize, outputBuffer);
        }
    }

    public byte[] jerToUper(String jer) {
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment inputBuffer = arena.allocate(textBufferSize);
            jerToTumData(arena, jer, tumData, inputBuffer);
            MemorySegment outputBuffer = arena.allocate(uperBufferSize);
            return tumDataToUper(arena, tumData, uperBufferSize, outputBuffer);
        }
    }

    public String uperToXer(byte[] uper) {
        log.trace("Received {} bytes", uper.length);
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment outputBuffer = arena.allocate(textBufferSize);
            MemorySegment inputBuffer = arena.allocate(uperBufferSize);
            return uperToXer(uper, arena, tumData, textBufferSize, outputBuffer, inputBuffer);
        }
    }

    public String uperToXer(byte[] uper, Arena arena, MemorySegment tumData, long bufferSize, MemorySegment outputBuffer,
                            MemorySegment inputBuffer) {
        uperToTumData(arena, uper, tumData, inputBuffer);
        return tumDataToXer(arena, tumData, bufferSize, outputBuffer);
    }

    public String uperToJer(byte[] uper) {
        log.trace("Received {} bytes", uper.length);
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment inputBuffer = arena.allocate(uperBufferSize);
            uperToTumData(arena, uper, tumData, inputBuffer);
            MemorySegment outputBuffer = arena.allocate(textBufferSize);
            return tumDataToJer(arena, tumData, textBufferSize, outputBuffer);
        }
    }

    public String xerToJer(String xer) {
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment inputBuffer = arena.allocate(textBufferSize);
            xerToTumData(arena, xer, tumData, inputBuffer);
            MemorySegment outputBuffer = arena.allocate(textBufferSize);
            return tumDataToJer(arena, tumData, textBufferSize, outputBuffer);
        }
    }

    public String jerToXer(String jer) {
        try (var arena = Arena.ofConfined()) {
            MemorySegment tumData = arena.allocate(tumDataAllocateSize);
            MemorySegment inputBuffer = arena.allocate(textBufferSize);
            jerToTumData(arena, jer, tumData, inputBuffer);
            MemorySegment outputBuffer = arena.allocate(textBufferSize);
            return tumDataToXer(arena, tumData, textBufferSize, outputBuffer);
        }
    }

    private void printTumData(Arena arena, MemorySegment tumData) {
        log.trace("Printing message frame");
        int printResult = asn_fprint(stdout(), asn_DEF_TumData(), tumData);
        log.trace("Printed message frame to stdout, result: " + printResult);
    }

    private void decodeToTumData(Arena arena, final byte[] bytes, final int asnTransferSyntax,
                                               MemorySegment tumData, MemorySegment inputBuffer) {
        log.trace("decodeToTumData, num bytes: {}, transfer syntax: {}", bytes.length,
                asnTransferSyntax);

        MemorySegment heapBytes = MemorySegment.ofArray(bytes);
        MemorySegment optCodecParameters = optCodecParameters(arena);

        // The result Message Frame
        //
        // Allocate the memory to receive a TumData_t structure, because passing a pointer to 0 and having the
        // decoder create the structure dynamically, as the C API docs recommend, would create a memory leak, because
        // since we don't know the size of the created struct we can't reinterpret and free the memory using
        // malloc/free, nor do we have access to the ASN_STRUCT_FREE macro from here.
        //
        // TODO Create a C header and function to expose ASN_STRUCT_FREE to FFM
        // Also see https://docs.oracle.com/en/java/javase/23/core/foreign-functions-that-return-pointers.html
        //
        // Meanwhile, instead, pre-allocate a buffer large enough to handle the expected size of the returned data
        // structure, managed by the memory arena, so it will be freed at the end of the try-with-resources.
        //
        // UPER decoding fails using TumData_t.allocate(),  probably because the TumData value is an ASN.1
        // open type whose size can't be determined just from the top level struct, so preallocate a fixed buffer size
        // to make sure it is large enough.
        //MemorySegment tumData = arena.allocate(tumDataAllocateSize);

        // Pointer to result TumData
        MemorySegment structurePtr = arena.allocate(ValueLayout.ADDRESS.byteSize());

        // We  assume the address is a Java long.  But if the FFM code were recompiled on a platform other than x64,
        // this wouldn't necessarily be true.
        assert ValueLayout.ADDRESS.byteSize() == ValueLayout.JAVA_LONG.byteSize();

        // Point to the preallocated TumData buffer
        structurePtr.set(ValueLayout.JAVA_LONG, 0, tumData.address());

        // Pointer to 0 that we are not using for now
        //structurePtr.set(ValueLayout.JAVA_LONG, 0, 0L);

        //MemorySegment buffer = arena.allocate(bytes.length);
        inputBuffer.copyFrom(heapBytes);
        MemorySegment er;

        er = asn_decode(arena, optCodecParameters, asnTransferSyntax, asn_DEF_TumData(), structurePtr,
                inputBuffer, bytes.length);

        long retCode = asn_dec_rval_t.code(er);
        long consumed = asn_dec_rval_t.consumed(er);
        String rcEnum = switch ((int)retCode) {
            case 0 -> "RC_OK";
            case 1 -> "RC_WMORE";
            case 2 -> "RC_FAIL";
            default -> "Unknown return code";
        };

        var msg = String.format("asn_decode return code: %s %s, consumed: %s", retCode, rcEnum, consumed);
        long tumDataPointer = structurePtr.get(ValueLayout.JAVA_LONG, 0);
        log.trace("tumData pointer: {}", tumDataPointer);

        // This is how to get the externally allocated TumData.  It works, but don't do it without
        // reinterpreting and freeing.
        //MemorySegment tumData = MemorySegment.ofAddress(structurePtr.get(ValueLayout.JAVA_LONG, 0));

        if (retCode == 0) {
            log.trace(msg);
        } else {
            // Print partially decoded data
            printTumData(arena, tumData);
            throw new RuntimeException("decode encountered error or RC_WMORE condition: " + msg);
        }

        //return tumData;
    }

    private void xerToTumData(Arena arena, String xer, MemorySegment tumData, MemorySegment inputBuffer) {
        log.trace("xerToTumData");
        byte[] xmlBytes = xer.getBytes(StandardCharsets.UTF_8);
        decodeToTumData(arena, xmlBytes, ATS_CANONICAL_XER(), tumData, inputBuffer);
    }

    private void jerToTumData(Arena arena, String jer, MemorySegment tumData, MemorySegment inputBuffer) {
        log.trace("jerToTumData");
        byte[] jsonBytes = jer.getBytes(StandardCharsets.UTF_8);
        decodeToTumData(arena, jsonBytes, ATS_JER(), tumData, inputBuffer);
    }

    private void uperToTumData(Arena arena, byte[] uper, MemorySegment tumData, MemorySegment inputBuffer) {
        log.trace("uperToTumData");
        decodeToTumData(arena, uper, ATS_UNALIGNED_BASIC_PER(), tumData, inputBuffer);
    }

    private byte[] encodeFromTumData(Arena arena, MemorySegment tumData, final int asnTransferSyntax,
                                          final long bufferSize, MemorySegment outputBuffer) {
        log.trace("encodeFromTumData, transferSyntax: {}, bufferSize: {}", asnTransferSyntax, bufferSize);
        MemorySegment optCodecParameters = optCodecParameters(arena);
        MemorySegment erEnc = asn_encode_to_buffer(arena, optCodecParameters, asnTransferSyntax,
                asn_DEF_TumData(), tumData, outputBuffer, bufferSize);
        long encoded = asn_enc_rval_t.encoded(erEnc);
        if (encoded > -1) {
            log.trace("asn_encode_to_buffer succeeded. Encoded {} bytes", encoded);
            byte[] outputArray = new byte[(int) encoded];
            MemorySegment heapOutput = MemorySegment.ofArray(outputArray);
            MemorySegment.copy(outputBuffer, 0, heapOutput, 0, encoded);
            return outputArray;
        } else {
            log.trace("Error in asn_encode_to_buffer");
            throw new RuntimeException("Error calling asn_encode_to_buffer");
            // Check the error info
            // fprintf(stderr, ”Cannot encode %s: %s\n”, er.failed_type >name, strerror(errno))
            // Need c function to expose errno macro
        }
    }

    private byte[] tumDataToUper(Arena arena, MemorySegment tumData, long bufferSize, MemorySegment outputBuffer) {
        log.trace("tumDataToUper");
        return encodeFromTumData(arena, tumData, ATS_UNALIGNED_BASIC_PER(), bufferSize, outputBuffer);
    }

    private String tumDataToXer(Arena arena, MemorySegment tumData, long bufferSize, MemorySegment outputBuffer) {
        log.trace("tumDataToXer");
        byte[] bytes = encodeFromTumData(arena, tumData, ATS_CANONICAL_XER(), bufferSize, outputBuffer);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    private String tumDataToJer(Arena arena, MemorySegment tumData, long bufferSize, MemorySegment outputBuffer) {
        log.trace("tumDataToJer");
        byte[] bytes = encodeFromTumData(arena, tumData, ATS_JER(), bufferSize, outputBuffer);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    private MemorySegment optCodecParameters(Arena arena) {
        MemorySegment optCodecParameters = asn_codec_ctx_t.allocate(arena);
        asn_codec_ctx_t.max_stack_size(optCodecParameters, asnCodecCtxMaxStackSize);
        return optCodecParameters;
    }


}
