# Publish a snapshot that follows all PRs or pushes to the 'snapshot' branch
name: Publish JARs to the Maven Central Repository (Snapshots)
on:
  push:
    branches:
      - snapshot
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: '8.13'

      - name: Publish Snapshot to Maven Central
        run: |
          chmod +x gradlew
          ./gradlew jreleaserPublish
        working-directory: j2735-2024-ffm-lib
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_TOKEN: ${{ secrets.JRELEASER_NEXUS2_TOKEN }}
          JRELEASER_GITHUB_TOKEN: 'dummy-github-token-dont-release-to-github'
